
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "System.xsd.h"
#include "DataModel.Model.xsd.h"

typedef struct _DataModel_Model_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // ArrayOfUser
        {
            struct  // User
            {
                WS_FIELD_DESCRIPTION Active;
                WS_FIELD_DESCRIPTION Birthdate;
                WS_FIELD_DESCRIPTION Email;
                WS_FIELD_DESCRIPTION FriendshipList;
                WS_FIELD_DESCRIPTION FriendshipRequestList;
                WS_FIELD_DESCRIPTION IdPermission;
                WS_FIELD_DESCRIPTION IdUser;
                WS_FIELD_DESCRIPTION Name;
                WS_FIELD_DESCRIPTION Password;
                WS_FIELD_DESCRIPTION Points;
                WS_FIELD_DESCRIPTION RelationshipRequestNegociation;
                struct  // Tag
                {
                    WS_FIELD_DESCRIPTION IdTag;
                    WS_FIELD_DESCRIPTION TagName;
                    WS_FIELD_DESCRIPTION* TagFields [2]; 
                } Tagdescs; // end of Tag
                WS_FIELD_DESCRIPTION UserTags;
                WS_FIELD_DESCRIPTION Username;
                WS_FIELD_DESCRIPTION* UserFields [13]; 
            } Userdescs; // end of User
            WS_FIELD_DESCRIPTION User;
            WS_FIELD_DESCRIPTION* ArrayOfUserFields [1]; 
        } ArrayOfUserdescs; // end of ArrayOfUser
        struct  // ArrayOfGameRequest
        {
            struct  // GameRequest
            {
                WS_FIELD_DESCRIPTION Difficulty;
                WS_FIELD_DESCRIPTION Status;
                WS_FIELD_DESCRIPTION* GameRequestFields [5]; 
            } GameRequestdescs; // end of GameRequest
            WS_FIELD_DESCRIPTION GameRequest;
            WS_FIELD_DESCRIPTION* ArrayOfGameRequestFields [1]; 
        } ArrayOfGameRequestdescs; // end of ArrayOfGameRequest
        struct  // Game
        {
            WS_FIELD_DESCRIPTION _type;
            WS_FIELD_DESCRIPTION GameName;
            WS_FIELD_DESCRIPTION IdGame;
            WS_FIELD_DESCRIPTION* GameFields [3]; 
            WS_STRUCT_DESCRIPTION* SubTypes[1];
        } Gamedescs; // end of Game
        struct  // ArrayOfTag
        {
            WS_FIELD_DESCRIPTION Tag;
            WS_FIELD_DESCRIPTION* ArrayOfTagFields [1]; 
        } ArrayOfTagdescs; // end of ArrayOfTag
    } globalTypes;  // end of global types
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING ArrayOfUserTypeName;  // ArrayOfUser
            WS_XML_STRING ArrayOfUserTypeNamespace;  // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_XML_STRING UserTypeName;  // User
            WS_XML_STRING UserActiveLocalName;  // Active
            WS_XML_STRING UserBirthdateLocalName;  // Birthdate
            WS_XML_STRING UserEmailLocalName;  // Email
            WS_XML_STRING UserFriendshipListLocalName;  // TupleOfintdateTimeTag2Xw_Sbs0H
            WS_XML_STRING UserFriendshipListNamespace;  // http://schemas.datacontract.org/2004/07/System
            WS_XML_STRING UserFriendshipListWrapperName;  // FriendshipList
            WS_XML_STRING UserFriendshipRequestListLocalName;  // TupleOfintdateTime
            WS_XML_STRING UserFriendshipRequestListWrapperName;  // FriendshipRequestList
            WS_XML_STRING UserIdPermissionLocalName;  // IdPermission
            WS_XML_STRING UserIdUserLocalName;  // IdUser
            WS_XML_STRING UserNameLocalName;  // Name
            WS_XML_STRING UserPasswordLocalName;  // Password
            WS_XML_STRING UserPointsLocalName;  // Points
            WS_XML_STRING UserRelationshipRequestNegociationLocalName;  // TupleOfintArrayOfGameRequestDj_S7S2QP
            WS_XML_STRING UserRelationshipRequestNegociationWrapperName;  // RelationshipRequestNegociation
            WS_XML_STRING TagTypeName;  // Tag
            WS_XML_STRING TagIdTagLocalName;  // IdTag
            WS_XML_STRING TagTagNameLocalName;  // TagName
            WS_XML_STRING UserUserTagsWrapperName;  // UserTags
            WS_XML_STRING UserUsernameLocalName;  // Username
            WS_XML_STRING ArrayOfGameRequestTypeName;  // ArrayOfGameRequest
            WS_XML_STRING GameRequestTypeName;  // GameRequest
            WS_XML_STRING GameRequestDifficultyLocalName;  // Difficulty
            WS_XML_STRING GameRequestStatusLocalName;  // Status
            WS_XML_STRING GameTypeName;  // Game
            WS_XML_STRING GameGameNameLocalName;  // GameName
            WS_XML_STRING GameIdGameLocalName;  // IdGame
            WS_XML_STRING ArrayOfTagTypeName;  // ArrayOfTag
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _DataModel_Model_xsdLocalDefinitions;

const static _DataModel_Model_xsdLocalDefinitions DataModel_Model_xsdLocalDefinitions =
{
    { // global types
        0,
        {  // ArrayOfUser
            {  // User
                {  // field description for Active
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserActiveLocalName, // Active
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_BOOL_TYPE,
                0,
                WsOffsetOf(User, Active),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Active
                {  // field description for Birthdate
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserBirthdateLocalName, // Birthdate
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_DATETIME_TYPE,
                0,
                WsOffsetOf(User, Birthdate),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Birthdate
                {  // field description for Email
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserEmailLocalName, // Email
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(User, Email),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Email
                {  // field description for FriendshipList
                WS_REPEATING_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserFriendshipListWrapperName, // FriendshipList
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_STRUCT_TYPE,
                (void*)&System_xsd.globalTypes.TupleOfintdateTimeTag2Xw_Sbs0H,
                WsOffsetOf(User, FriendshipList),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
                0,
                WsOffsetOf(User, FriendshipListCount),
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserFriendshipListLocalName, // TupleOfintdateTimeTag2Xw_Sbs0H
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserFriendshipListNamespace, // http://schemas.datacontract.org/2004/07/System
                0,
                },    // end of field description for FriendshipList
                {  // field description for FriendshipRequestList
                WS_REPEATING_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserFriendshipRequestListWrapperName, // FriendshipRequestList
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_STRUCT_TYPE,
                (void*)&System_xsd.globalTypes.TupleOfintdateTime,
                WsOffsetOf(User, FriendshipRequestList),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
                0,
                WsOffsetOf(User, FriendshipRequestListCount),
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserFriendshipRequestListLocalName, // TupleOfintdateTime
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserFriendshipListNamespace, // http://schemas.datacontract.org/2004/07/System
                0,
                },    // end of field description for FriendshipRequestList
                {  // field description for IdPermission
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserIdPermissionLocalName, // IdPermission
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_INT32_TYPE,
                0,
                WsOffsetOf(User, IdPermission),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for IdPermission
                {  // field description for IdUser
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserIdUserLocalName, // IdUser
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_INT32_TYPE,
                0,
                WsOffsetOf(User, IdUser),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for IdUser
                {  // field description for Name
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserNameLocalName, // Name
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(User, Name),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Name
                {  // field description for Password
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserPasswordLocalName, // Password
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(User, Password),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Password
                {  // field description for Points
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserPointsLocalName, // Points
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_INT32_TYPE,
                0,
                WsOffsetOf(User, Points),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Points
                {  // field description for RelationshipRequestNegociation
                WS_REPEATING_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserRelationshipRequestNegociationWrapperName, // RelationshipRequestNegociation
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_STRUCT_TYPE,
                (void*)&System_xsd.globalTypes.TupleOfintArrayOfGameRequestDj_S7S2QP,
                WsOffsetOf(User, RelationshipRequestNegociation),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
                0,
                WsOffsetOf(User, RelationshipRequestNegociationCount),
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserRelationshipRequestNegociationLocalName, // TupleOfintArrayOfGameRequestDj_S7S2QP
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserFriendshipListNamespace, // http://schemas.datacontract.org/2004/07/System
                0,
                },    // end of field description for RelationshipRequestNegociation
                {  // Tag
                    {  // field description for IdTag
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.TagIdTagLocalName, // IdTag
                    (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                    WS_INT32_TYPE,
                    0,
                    WsOffsetOf(Tag, IdTag),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for IdTag
                    {  // field description for TagName
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.TagTagNameLocalName, // TagName
                    (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(Tag, TagName),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                    0,
                    0xffffffff
                    },    // end of field description for TagName
                    {  // fields description for Tag
                    (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Tagdescs.IdTag,
                    (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Tagdescs.TagName,
                    },
                },    // Tag
                {  // field description for UserTags
                WS_REPEATING_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserUserTagsWrapperName, // UserTags
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_STRUCT_TYPE,
                (void*)&DataModel_Model_xsd.globalTypes.Tag,
                WsOffsetOf(User, UserTags),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
                0,
                WsOffsetOf(User, UserTagsCount),
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                0,
                },    // end of field description for UserTags
                {  // field description for Username
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserUsernameLocalName, // Username
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(User, Username),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Username
                {  // fields description for User
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Active,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Birthdate,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Email,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.FriendshipList,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.FriendshipRequestList,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.IdPermission,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.IdUser,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Name,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Password,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Points,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.RelationshipRequestNegociation,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.UserTags,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Username,
                },
            },    // User
            {  // field description for User
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.User,
            WsOffsetOf(ArrayOfUser, User),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfUser, UserCount),
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            0,
            },    // end of field description for User
            {  // fields description for ArrayOfUser
            (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.User,
            },
        },    // ArrayOfUser
        {  // ArrayOfGameRequest
            {  // GameRequest
                {  // field description for Difficulty
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameRequestDifficultyLocalName, // Difficulty
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_INT32_TYPE,
                0,
                WsOffsetOf(GameRequest, Difficulty),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Difficulty
                {  // field description for Status
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameRequestStatusLocalName, // Status
                (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
                WS_BOOL_TYPE,
                0,
                WsOffsetOf(GameRequest, Status),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Status
                {  // fields description for GameRequest
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs._type,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs.GameName,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs.IdGame,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfGameRequestdescs.GameRequestdescs.Difficulty,
                (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfGameRequestdescs.GameRequestdescs.Status,
                },
            },    // GameRequest
            {  // field description for GameRequest
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.GameRequest,
            WsOffsetOf(ArrayOfGameRequest, GameRequest),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfGameRequest, GameRequestCount),
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameRequestTypeName, // GameRequest
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            0,
            },    // end of field description for GameRequest
            {  // fields description for ArrayOfGameRequest
            (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfGameRequestdescs.GameRequest,
            },
        },    // ArrayOfGameRequest
        {  // Game
            {  // field description for _type
            WS_TYPE_ATTRIBUTE_FIELD_MAPPING,
            0,
            0,
            WS_DESCRIPTION_TYPE,
            0,
            WsOffsetOf(Game, _type),
            0,
            0,
            0xffffffff
            },    // end of field description for _type
            {  // field description for GameName
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameGameNameLocalName, // GameName
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Game, GameName),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for GameName
            {  // field description for IdGame
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameIdGameLocalName, // IdGame
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_INT32_TYPE,
            0,
            WsOffsetOf(Game, IdGame),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for IdGame
            {  // fields description for Game
            (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs._type,
            (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs.GameName,
            (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs.IdGame,
            },
            {  // array of sub types struct description
                (WS_STRUCT_DESCRIPTION*)&DataModel_Model_xsd.globalTypes.GameRequest,
            }, //array of sub types struct description
        },    // Game
        {  // ArrayOfTag
            {  // field description for Tag
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.Tag,
            WsOffsetOf(ArrayOfTag, Tag),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfTag, TagCount),
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            0,
            },    // end of field description for Tag
            {  // fields description for ArrayOfTag
            (WS_FIELD_DESCRIPTION*)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfTagdescs.Tag,
            },
        },    // ArrayOfTag
    }, // end of global types
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfUser",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/DataModel.Model",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("User",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Active",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("Birthdate",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("Email",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("TupleOfintdateTimeTag2Xw_Sbs0H",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/System",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("FriendshipList",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("TupleOfintdateTime",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("FriendshipRequestList",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("IdPermission",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("IdUser",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("Name",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("Password",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("Points",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("TupleOfintArrayOfGameRequestDj_S7S2QP",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("RelationshipRequestNegociation",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("Tag",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("IdTag",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("TagName",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("UserTags",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("Username",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfGameRequest",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("GameRequest",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("Difficulty",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("Status",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("Game",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 27),
            WS_XML_STRING_DICTIONARY_VALUE("GameName",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 28),
            WS_XML_STRING_DICTIONARY_VALUE("IdGame",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 29),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfTag",&DataModel_Model_xsdLocalDefinitions.dictionary.dict, 30),
        },  // end of xmlStrings
        
        {  // DataModel_Model_xsddictionary
          // 50e396f9-c415-473d-9514-1df2ca65a045 
        { 0x50e396f9, 0xc415, 0x473d, { 0x95, 0x14, 0x1d,0xf2, 0xca, 0x65, 0xa0, 0x45 } },
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings,
        31,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of DataModel_Model_xsdLocalDefinitions

const _DataModel_Model_xsd DataModel_Model_xsd =
{
    {  // globalTypes
        {
        sizeof(ArrayOfUser),
        __alignof(ArrayOfUser),
        (WS_FIELD_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.ArrayOfUserFields,
        WsCountOf(DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.ArrayOfUserFields),
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeName, // ArrayOfUser
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
        0,
        0,
        0,
        },   // end of struct description for ArrayOfUser
        {
        sizeof(User),
        __alignof(User),
        (WS_FIELD_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.UserFields,
        WsCountOf(DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.UserFields),
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
        0,
        0,
        0,
        },   // end of struct description for User
        {
        sizeof(Tag),
        __alignof(Tag),
        (WS_FIELD_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Tagdescs.TagFields,
        WsCountOf(DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.Userdescs.Tagdescs.TagFields),
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
        0,
        0,
        0,
        },   // end of struct description for Tag
        {
        sizeof(ArrayOfGameRequest),
        __alignof(ArrayOfGameRequest),
        (WS_FIELD_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfGameRequestdescs.ArrayOfGameRequestFields,
        WsCountOf(DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfGameRequestdescs.ArrayOfGameRequestFields),
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfGameRequestTypeName, // ArrayOfGameRequest
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
        0,
        0,
        0,
        },   // end of struct description for ArrayOfGameRequest
        {
        sizeof(GameRequest),
        __alignof(GameRequest),
        (WS_FIELD_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfGameRequestdescs.GameRequestdescs.GameRequestFields,
        WsCountOf(DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfGameRequestdescs.GameRequestdescs.GameRequestFields),
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameRequestTypeName, // GameRequest
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
        0,
        0,
        0,
        },   // end of struct description for GameRequest
        {
        sizeof(Game),
        __alignof(Game),
        (WS_FIELD_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs.GameFields,
        WsCountOf(DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs.GameFields),
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameTypeName, // Game
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
        0,
        (WS_STRUCT_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.Gamedescs.SubTypes,
        1,
        },   // end of struct description for Game
        {
        sizeof(ArrayOfTag),
        __alignof(ArrayOfTag),
        (WS_FIELD_DESCRIPTION**)&DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfTagdescs.ArrayOfTagFields,
        WsCountOf(DataModel_Model_xsdLocalDefinitions.globalTypes.ArrayOfTagdescs.ArrayOfTagFields),
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfTagTypeName, // ArrayOfTag
        (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
        0,
        0,
        0,
        },   // end of struct description for ArrayOfTag
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeName, // ArrayOfUser
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.ArrayOfUser,
        },
        {
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.User,
        },
        {
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.Tag,
        },
        {
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfGameRequestTypeName, // ArrayOfGameRequest
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.ArrayOfGameRequest,
        },
        {
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameRequestTypeName, // GameRequest
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.GameRequest,
        },
        {
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.GameTypeName, // Game
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.Game,
        },
        {
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfTagTypeName, // ArrayOfTag
            (WS_XML_STRING*)&DataModel_Model_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.ArrayOfTag,
        },
    },  // globalElements
}; // end of _DataModel_Model_xsd

#if !defined(WS_CPLUSPLUS)

struct GameRequest* WINAPI Game_AsGameRequest(Game* _Game)
{
    if (((Game*)_Game)->_type == 
        (WS_STRUCT_DESCRIPTION*)&DataModel_Model_xsd.globalTypes.GameRequest)
        return (GameRequest*)_Game;
    return 0;
}
void WINAPI GameRequest_Init(GameRequest* _GameRequest)
{
    ((Game*)_GameRequest)->_type = 
        (WS_STRUCT_DESCRIPTION*)&DataModel_Model_xsd.globalTypes.GameRequest;
}
#endif

#if defined(WS_CPLUSPLUS)
GameRequest::GameRequest() 
    : Game((WS_STRUCT_DESCRIPTION*)&DataModel_Model_xsd.globalTypes.GameRequest)
{
}
#endif

#if !defined(WS_CPLUSPLUS)
void WINAPI Game_Init(Game* _Game)
{
    ((Game*)_Game)->_type = 
        (WS_STRUCT_DESCRIPTION*)&DataModel_Model_xsd.globalTypes.Game;
}
#endif

#if defined(WS_CPLUSPLUS)
Game::Game() 
{
    this->_type = (WS_STRUCT_DESCRIPTION*)&DataModel_Model_xsd.globalTypes.Game;
}

Game::Game(WS_STRUCT_DESCRIPTION* _structDesc)
{
    this->_type = _structDesc;
}

struct GameRequest* WINAPI Game::AsGameRequest()
{
    if (this->_type == (WS_STRUCT_DESCRIPTION*)&DataModel_Model_xsd.globalTypes.GameRequest)
        return (GameRequest*)this;
    return 0;
}
#endif
