
// File generated by Wsutil Compiler version 1.0095 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by Wsutil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct ArrayOfUserType;
//     struct UserType;
//     struct ArrayOfUserType;
//     struct UserType;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: GameWS_xsd.globalTypes.ArrayOfUserType
typedef struct ArrayOfUserType 
{
    unsigned int UserTypeCount;
    _Field_size_(UserTypeCount)struct UserType** UserType; // optional
} ArrayOfUserType;

// typeDescription: GameWS_xsd.globalTypes.UserType
typedef struct UserType 
{
    WCHAR* FriendshipList; // optional
    WCHAR* FriendshipRequestList; // optional
    int IdUser;
    WCHAR* Name; // optional
    int Points;
    WCHAR* RelationshipRequestNegociation; // optional
    WCHAR* UserTags; // optional
    WCHAR* Username; // optional
} UserType;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _GameWS_xsd
{
    struct // globalTypes
    {
        // xml type: ArrayOfUserType ("http://schemas.datacontract.org/2004/07/GameWS")
        // c type: ArrayOfUserType
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: GameWS_xsd.globalTypes.ArrayOfUserType
        WS_STRUCT_DESCRIPTION ArrayOfUserType;
        
        // xml type: UserType ("http://schemas.datacontract.org/2004/07/GameWS")
        // c type: UserType
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: GameWS_xsd.globalTypes.UserType
        WS_STRUCT_DESCRIPTION UserType;
        
    } globalTypes;
    struct // globalElements
    {
        // xml element: ArrayOfUserType ("http://schemas.datacontract.org/2004/07/GameWS")
        // c type: ArrayOfUserType
        // elementDescription: GameWS_xsd.globalElements.ArrayOfUserType
        WS_ELEMENT_DESCRIPTION ArrayOfUserType;
        
        // xml element: UserType ("http://schemas.datacontract.org/2004/07/GameWS")
        // c type: UserType
        // elementDescription: GameWS_xsd.globalElements.UserType
        WS_ELEMENT_DESCRIPTION UserType;
        
    } globalElements;
} _GameWS_xsd;

extern const _GameWS_xsd GameWS_xsd;

#ifdef __cplusplus
}
#endif

