
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "GameWS.xsd.h"

typedef struct _GameWS_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // ArrayOfUserType
        {
            struct  // UserType
            {
                WS_FIELD_DESCRIPTION FriendshipList;
                WS_FIELD_DESCRIPTION FriendshipRequestList;
                WS_FIELD_DESCRIPTION IdUser;
                WS_FIELD_DESCRIPTION MoodState;
                WS_FIELD_DESCRIPTION Name;
                WS_FIELD_DESCRIPTION Points;
                WS_FIELD_DESCRIPTION RelationshipRequestNegociation;
                WS_FIELD_DESCRIPTION UserTags;
                WS_FIELD_DESCRIPTION Username;
                WS_FIELD_DESCRIPTION* UserTypeFields [9]; 
            } UserTypedescs; // end of UserType
            WS_FIELD_DESCRIPTION UserType;
            WS_FIELD_DESCRIPTION* ArrayOfUserTypeFields [1]; 
        } ArrayOfUserTypedescs; // end of ArrayOfUserType
        struct  // ArrayOfDict
        {
            struct  // Dict
            {
                WS_FIELD_DESCRIPTION IdDict;
                WS_FIELD_DESCRIPTION TagsUsed;
                WS_FIELD_DESCRIPTION Word;
                WS_FIELD_DESCRIPTION* DictFields [3]; 
            } Dictdescs; // end of Dict
            WS_FIELD_DESCRIPTION Dict;
            WS_FIELD_DESCRIPTION* ArrayOfDictFields [1]; 
        } ArrayOfDictdescs; // end of ArrayOfDict
    } globalTypes;  // end of global types
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING ArrayOfUserTypeTypeName;  // ArrayOfUserType
            WS_XML_STRING ArrayOfUserTypeTypeNamespace;  // http://schemas.datacontract.org/2004/07/GameWS
            WS_XML_STRING UserTypeTypeName;  // UserType
            WS_XML_STRING UserTypeFriendshipListLocalName;  // FriendshipList
            WS_XML_STRING UserTypeFriendshipRequestListLocalName;  // FriendshipRequestList
            WS_XML_STRING UserTypeIdUserLocalName;  // IdUser
            WS_XML_STRING UserTypeMoodStateLocalName;  // MoodState
            WS_XML_STRING UserTypeNameLocalName;  // Name
            WS_XML_STRING UserTypePointsLocalName;  // Points
            WS_XML_STRING UserTypeRelationshipRequestNegociationLocalName;  // RelationshipRequestNegociation
            WS_XML_STRING UserTypeUserTagsLocalName;  // UserTags
            WS_XML_STRING UserTypeUsernameLocalName;  // Username
            WS_XML_STRING ArrayOfDictTypeName;  // ArrayOfDict
            WS_XML_STRING DictTypeName;  // Dict
            WS_XML_STRING DictIdDictLocalName;  // IdDict
            WS_XML_STRING DictTagsUsedLocalName;  // TagsUsed
            WS_XML_STRING DictWordLocalName;  // Word
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _GameWS_xsdLocalDefinitions;

const static _GameWS_xsdLocalDefinitions GameWS_xsdLocalDefinitions =
{
    { // global types
        0,
        {  // ArrayOfUserType
            {  // UserType
                {  // field description for FriendshipList
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeFriendshipListLocalName, // FriendshipList
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, FriendshipList),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for FriendshipList
                {  // field description for FriendshipRequestList
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeFriendshipRequestListLocalName, // FriendshipRequestList
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, FriendshipRequestList),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for FriendshipRequestList
                {  // field description for IdUser
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeIdUserLocalName, // IdUser
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_INT32_TYPE,
                0,
                WsOffsetOf(UserType, IdUser),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for IdUser
                {  // field description for MoodState
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeMoodStateLocalName, // MoodState
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_INT32_TYPE,
                0,
                WsOffsetOf(UserType, MoodState),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for MoodState
                {  // field description for Name
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNameLocalName, // Name
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, Name),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Name
                {  // field description for Points
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypePointsLocalName, // Points
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_INT32_TYPE,
                0,
                WsOffsetOf(UserType, Points),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Points
                {  // field description for RelationshipRequestNegociation
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeRelationshipRequestNegociationLocalName, // RelationshipRequestNegociation
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, RelationshipRequestNegociation),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for RelationshipRequestNegociation
                {  // field description for UserTags
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeUserTagsLocalName, // UserTags
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, UserTags),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for UserTags
                {  // field description for Username
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeUsernameLocalName, // Username
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, Username),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Username
                {  // fields description for UserType
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.FriendshipList,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.FriendshipRequestList,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.IdUser,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.MoodState,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.Name,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.Points,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.RelationshipRequestNegociation,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.UserTags,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.Username,
                },
            },    // UserType
            {  // field description for UserType
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
            WsOffsetOf(ArrayOfUserType, UserType),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfUserType, UserTypeCount),
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeTypeName, // UserType
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            0,
            },    // end of field description for UserType
            {  // fields description for ArrayOfUserType
            (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserType,
            },
        },    // ArrayOfUserType
        {  // ArrayOfDict
            {  // Dict
                {  // field description for IdDict
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.DictIdDictLocalName, // IdDict
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Dict, IdDict),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for IdDict
                {  // field description for TagsUsed
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.DictTagsUsedLocalName, // TagsUsed
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Dict, TagsUsed),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for TagsUsed
                {  // field description for Word
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.DictWordLocalName, // Word
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Dict, Word),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Word
                {  // fields description for Dict
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.Dictdescs.IdDict,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.Dictdescs.TagsUsed,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.Dictdescs.Word,
                },
            },    // Dict
            {  // field description for Dict
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.Dict,
            WsOffsetOf(ArrayOfDict, Dict),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfDict, DictCount),
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.DictTypeName, // Dict
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            0,
            },    // end of field description for Dict
            {  // fields description for ArrayOfDict
            (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.Dict,
            },
        },    // ArrayOfDict
    }, // end of global types
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfUserType",&GameWS_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/GameWS",&GameWS_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("UserType",&GameWS_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("FriendshipList",&GameWS_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("FriendshipRequestList",&GameWS_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("IdUser",&GameWS_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("MoodState",&GameWS_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("Name",&GameWS_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("Points",&GameWS_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("RelationshipRequestNegociation",&GameWS_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("UserTags",&GameWS_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("Username",&GameWS_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfDict",&GameWS_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("Dict",&GameWS_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("IdDict",&GameWS_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("TagsUsed",&GameWS_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("Word",&GameWS_xsdLocalDefinitions.dictionary.dict, 16),
        },  // end of xmlStrings
        
        {  // GameWS_xsddictionary
          // ca8d4e9e-de0c-4f1e-9bce-5e30406137fe 
        { 0xca8d4e9e, 0xde0c, 0x4f1e, { 0x9b, 0xce, 0x5e,0x30, 0x40, 0x61, 0x37, 0xfe } },
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings,
        17,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of GameWS_xsdLocalDefinitions

const _GameWS_xsd GameWS_xsd =
{
    {  // globalTypes
        {
        sizeof(ArrayOfUserType),
        __alignof(ArrayOfUserType),
        (WS_FIELD_DESCRIPTION**)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.ArrayOfUserTypeFields,
        WsCountOf(GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.ArrayOfUserTypeFields),
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeName, // ArrayOfUserType
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
        0,
        0,
        0,
        },   // end of struct description for ArrayOfUserType
        {
        sizeof(UserType),
        __alignof(UserType),
        (WS_FIELD_DESCRIPTION**)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.UserTypeFields,
        WsCountOf(GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.UserTypeFields),
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeTypeName, // UserType
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
        0,
        0,
        0,
        },   // end of struct description for UserType
        {
        sizeof(ArrayOfDict),
        __alignof(ArrayOfDict),
        (WS_FIELD_DESCRIPTION**)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.ArrayOfDictFields,
        WsCountOf(GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.ArrayOfDictFields),
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfDictTypeName, // ArrayOfDict
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
        0,
        0,
        0,
        },   // end of struct description for ArrayOfDict
        {
        sizeof(Dict),
        __alignof(Dict),
        (WS_FIELD_DESCRIPTION**)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.Dictdescs.DictFields,
        WsCountOf(GameWS_xsdLocalDefinitions.globalTypes.ArrayOfDictdescs.Dictdescs.DictFields),
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.DictTypeName, // Dict
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
        0,
        0,
        0,
        },   // end of struct description for Dict
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeName, // ArrayOfUserType
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.ArrayOfUserType,
        },
        {
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeTypeName, // UserType
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
        },
        {
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfDictTypeName, // ArrayOfDict
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.ArrayOfDict,
        },
        {
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.DictTypeName, // Dict
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.Dict,
        },
    },  // globalElements
}; // end of _GameWS_xsd
