
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "GameWS.xsd.h"

typedef struct _GameWS_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // ArrayOfUserType
        {
            struct  // UserType
            {
                WS_FIELD_DESCRIPTION FriendshipList;
                WS_FIELD_DESCRIPTION FriendshipRequestList;
                WS_FIELD_DESCRIPTION IdUser;
                WS_FIELD_DESCRIPTION Name;
                WS_FIELD_DESCRIPTION Points;
                WS_FIELD_DESCRIPTION RelationshipRequestNegociation;
                WS_FIELD_DESCRIPTION UserTags;
                WS_FIELD_DESCRIPTION Username;
                WS_FIELD_DESCRIPTION* UserTypeFields [8]; 
            } UserTypedescs; // end of UserType
            WS_FIELD_DESCRIPTION UserType;
            WS_FIELD_DESCRIPTION* ArrayOfUserTypeFields [1]; 
        } ArrayOfUserTypedescs; // end of ArrayOfUserType
    } globalTypes;  // end of global types
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING ArrayOfUserTypeTypeName;  // ArrayOfUserType
            WS_XML_STRING ArrayOfUserTypeTypeNamespace;  // http://schemas.datacontract.org/2004/07/GameWS
            WS_XML_STRING UserTypeTypeName;  // UserType
            WS_XML_STRING UserTypeFriendshipListLocalName;  // FriendshipList
            WS_XML_STRING UserTypeFriendshipRequestListLocalName;  // FriendshipRequestList
            WS_XML_STRING UserTypeIdUserLocalName;  // IdUser
            WS_XML_STRING UserTypeNameLocalName;  // Name
            WS_XML_STRING UserTypePointsLocalName;  // Points
            WS_XML_STRING UserTypeRelationshipRequestNegociationLocalName;  // RelationshipRequestNegociation
            WS_XML_STRING UserTypeUserTagsLocalName;  // UserTags
            WS_XML_STRING UserTypeUsernameLocalName;  // Username
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _GameWS_xsdLocalDefinitions;

const static _GameWS_xsdLocalDefinitions GameWS_xsdLocalDefinitions =
{
    { // global types
        0,
        {  // ArrayOfUserType
            {  // UserType
                {  // field description for FriendshipList
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeFriendshipListLocalName, // FriendshipList
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, FriendshipList),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for FriendshipList
                {  // field description for FriendshipRequestList
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeFriendshipRequestListLocalName, // FriendshipRequestList
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, FriendshipRequestList),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for FriendshipRequestList
                {  // field description for IdUser
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeIdUserLocalName, // IdUser
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_INT32_TYPE,
                0,
                WsOffsetOf(UserType, IdUser),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for IdUser
                {  // field description for Name
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNameLocalName, // Name
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, Name),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Name
                {  // field description for Points
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypePointsLocalName, // Points
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_INT32_TYPE,
                0,
                WsOffsetOf(UserType, Points),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for Points
                {  // field description for RelationshipRequestNegociation
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeRelationshipRequestNegociationLocalName, // RelationshipRequestNegociation
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, RelationshipRequestNegociation),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for RelationshipRequestNegociation
                {  // field description for UserTags
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeUserTagsLocalName, // UserTags
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, UserTags),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for UserTags
                {  // field description for Username
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeUsernameLocalName, // Username
                (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(UserType, Username),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Username
                {  // fields description for UserType
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.FriendshipList,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.FriendshipRequestList,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.IdUser,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.Name,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.Points,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.RelationshipRequestNegociation,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.UserTags,
                (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.Username,
                },
            },    // UserType
            {  // field description for UserType
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
            WsOffsetOf(ArrayOfUserType, UserType),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfUserType, UserTypeCount),
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeTypeName, // UserType
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            0,
            },    // end of field description for UserType
            {  // fields description for ArrayOfUserType
            (WS_FIELD_DESCRIPTION*)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserType,
            },
        },    // ArrayOfUserType
    }, // end of global types
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfUserType",&GameWS_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/GameWS",&GameWS_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("UserType",&GameWS_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("FriendshipList",&GameWS_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("FriendshipRequestList",&GameWS_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("IdUser",&GameWS_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("Name",&GameWS_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("Points",&GameWS_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("RelationshipRequestNegociation",&GameWS_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("UserTags",&GameWS_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("Username",&GameWS_xsdLocalDefinitions.dictionary.dict, 10),
        },  // end of xmlStrings
        
        {  // GameWS_xsddictionary
          // 6d2c04c0-ebe2-419e-8260-60fc74e86359 
        { 0x6d2c04c0, 0xebe2, 0x419e, { 0x82, 0x60, 0x60,0xfc, 0x74, 0xe8, 0x63, 0x59 } },
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings,
        11,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of GameWS_xsdLocalDefinitions

const _GameWS_xsd GameWS_xsd =
{
    {  // globalTypes
        {
        sizeof(ArrayOfUserType),
        __alignof(ArrayOfUserType),
        (WS_FIELD_DESCRIPTION**)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.ArrayOfUserTypeFields,
        WsCountOf(GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.ArrayOfUserTypeFields),
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeName, // ArrayOfUserType
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
        0,
        0,
        0,
        },   // end of struct description for ArrayOfUserType
        {
        sizeof(UserType),
        __alignof(UserType),
        (WS_FIELD_DESCRIPTION**)&GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.UserTypeFields,
        WsCountOf(GameWS_xsdLocalDefinitions.globalTypes.ArrayOfUserTypedescs.UserTypedescs.UserTypeFields),
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeTypeName, // UserType
        (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
        0,
        0,
        0,
        },   // end of struct description for UserType
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeName, // ArrayOfUserType
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.ArrayOfUserType,
        },
        {
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeTypeName, // UserType
            (WS_XML_STRING*)&GameWS_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeTypeNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
        },
    },  // globalElements
}; // end of _GameWS_xsd
