
// File generated by Wsutil Compiler version 1.0095 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by Wsutil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H;
//     struct TupleOfintdateTimeTag2Xw_Sbs0H;
//     struct ArrayOfTupleOfintdateTime;
//     struct TupleOfintdateTime;
//     struct ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP;
//     struct TupleOfintArrayOfGameRequestDj_S7S2QP;
//     struct ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H;
//     struct TupleOfintdateTimeTag2Xw_Sbs0H;
//     struct ArrayOfTupleOfintdateTime;
//     struct TupleOfintdateTime;
//     struct ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP;
//     struct TupleOfintArrayOfGameRequestDj_S7S2QP;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "DataModel.Model.xsd.h"

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: System_xsd.globalTypes.ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H
typedef struct ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H 
{
    unsigned int TupleOfintdateTimeTag2Xw_Sbs0HCount;
    _Field_size_(TupleOfintdateTimeTag2Xw_Sbs0HCount)struct TupleOfintdateTimeTag2Xw_Sbs0H** TupleOfintdateTimeTag2Xw_Sbs0H; // optional
} ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H;

// typeDescription: System_xsd.globalTypes.TupleOfintdateTimeTag2Xw_Sbs0H
typedef struct TupleOfintdateTimeTag2Xw_Sbs0H 
{
    int m_Item1;
    WS_DATETIME m_Item2;
    struct Tag* m_Item3; // optional
} TupleOfintdateTimeTag2Xw_Sbs0H;

// typeDescription: System_xsd.globalTypes.ArrayOfTupleOfintdateTime
typedef struct ArrayOfTupleOfintdateTime 
{
    unsigned int TupleOfintdateTimeCount;
    _Field_size_(TupleOfintdateTimeCount)struct TupleOfintdateTime** TupleOfintdateTime; // optional
} ArrayOfTupleOfintdateTime;

// typeDescription: System_xsd.globalTypes.TupleOfintdateTime
typedef struct TupleOfintdateTime 
{
    int m_Item1;
    WS_DATETIME m_Item2;
} TupleOfintdateTime;

// typeDescription: System_xsd.globalTypes.ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP
typedef struct ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP 
{
    unsigned int TupleOfintArrayOfGameRequestDj_S7S2QPCount;
    _Field_size_(TupleOfintArrayOfGameRequestDj_S7S2QPCount)struct TupleOfintArrayOfGameRequestDj_S7S2QP** TupleOfintArrayOfGameRequestDj_S7S2QP; // optional
} ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP;

// typeDescription: System_xsd.globalTypes.TupleOfintArrayOfGameRequestDj_S7S2QP
typedef struct TupleOfintArrayOfGameRequestDj_S7S2QP 
{
    int m_Item1;
    unsigned int m_Item2Count;
    _Field_size_opt_(m_Item2Count)struct GameRequest** m_Item2; // optional
} TupleOfintArrayOfGameRequestDj_S7S2QP;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _System_xsd
{
    struct // globalTypes
    {
        // xml type: ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H ("http://schemas.datacontract.org/2004/07/System")
        // c type: ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: System_xsd.globalTypes.ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H
        WS_STRUCT_DESCRIPTION ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H;
        
        // xml type: TupleOfintdateTimeTag2Xw_Sbs0H ("http://schemas.datacontract.org/2004/07/System")
        // c type: TupleOfintdateTimeTag2Xw_Sbs0H
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: System_xsd.globalTypes.TupleOfintdateTimeTag2Xw_Sbs0H
        WS_STRUCT_DESCRIPTION TupleOfintdateTimeTag2Xw_Sbs0H;
        
        // xml type: ArrayOfTupleOfintdateTime ("http://schemas.datacontract.org/2004/07/System")
        // c type: ArrayOfTupleOfintdateTime
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: System_xsd.globalTypes.ArrayOfTupleOfintdateTime
        WS_STRUCT_DESCRIPTION ArrayOfTupleOfintdateTime;
        
        // xml type: TupleOfintdateTime ("http://schemas.datacontract.org/2004/07/System")
        // c type: TupleOfintdateTime
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: System_xsd.globalTypes.TupleOfintdateTime
        WS_STRUCT_DESCRIPTION TupleOfintdateTime;
        
        // xml type: ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP ("http://schemas.datacontract.org/2004/07/System")
        // c type: ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: System_xsd.globalTypes.ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP
        WS_STRUCT_DESCRIPTION ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP;
        
        // xml type: TupleOfintArrayOfGameRequestDj_S7S2QP ("http://schemas.datacontract.org/2004/07/System")
        // c type: TupleOfintArrayOfGameRequestDj_S7S2QP
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: System_xsd.globalTypes.TupleOfintArrayOfGameRequestDj_S7S2QP
        WS_STRUCT_DESCRIPTION TupleOfintArrayOfGameRequestDj_S7S2QP;
        
    } globalTypes;
    struct // globalElements
    {
        // xml element: ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H ("http://schemas.datacontract.org/2004/07/System")
        // c type: ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H
        // elementDescription: System_xsd.globalElements.ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H
        WS_ELEMENT_DESCRIPTION ArrayOfTupleOfintdateTimeTag2Xw_Sbs0H;
        
        // xml element: TupleOfintdateTimeTag2Xw_Sbs0H ("http://schemas.datacontract.org/2004/07/System")
        // c type: TupleOfintdateTimeTag2Xw_Sbs0H
        // elementDescription: System_xsd.globalElements.TupleOfintdateTimeTag2Xw_Sbs0H
        WS_ELEMENT_DESCRIPTION TupleOfintdateTimeTag2Xw_Sbs0H;
        
        // xml element: ArrayOfTupleOfintdateTime ("http://schemas.datacontract.org/2004/07/System")
        // c type: ArrayOfTupleOfintdateTime
        // elementDescription: System_xsd.globalElements.ArrayOfTupleOfintdateTime
        WS_ELEMENT_DESCRIPTION ArrayOfTupleOfintdateTime;
        
        // xml element: TupleOfintdateTime ("http://schemas.datacontract.org/2004/07/System")
        // c type: TupleOfintdateTime
        // elementDescription: System_xsd.globalElements.TupleOfintdateTime
        WS_ELEMENT_DESCRIPTION TupleOfintdateTime;
        
        // xml element: ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP ("http://schemas.datacontract.org/2004/07/System")
        // c type: ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP
        // elementDescription: System_xsd.globalElements.ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP
        WS_ELEMENT_DESCRIPTION ArrayOfTupleOfintArrayOfGameRequestDj_S7S2QP;
        
        // xml element: TupleOfintArrayOfGameRequestDj_S7S2QP ("http://schemas.datacontract.org/2004/07/System")
        // c type: TupleOfintArrayOfGameRequestDj_S7S2QP
        // elementDescription: System_xsd.globalElements.TupleOfintArrayOfGameRequestDj_S7S2QP
        WS_ELEMENT_DESCRIPTION TupleOfintArrayOfGameRequestDj_S7S2QP;
        
    } globalElements;
} _System_xsd;

extern const _System_xsd System_xsd;

#ifdef __cplusplus
}
#endif

