
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "GameWS.xsd.h"
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION IGameWebService_login_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_login_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_NR_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_NR_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserById_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserById_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_changeUserPoints_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_changeUserPoints_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_changeMoodState_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_changeMoodState_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_doNegociationGameComplete_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_doNegociationGameComplete_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_getDictionarys_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_getDictionarys_OutputMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // BasicHttpBinding_IGameWebService
        {
            struct  // BasicHttpBinding_IGameWebService_login
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_login;
            } BasicHttpBinding_IGameWebService_login;
            struct  // BasicHttpBinding_IGameWebService_loadUserNetwork
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserNetwork;
            } BasicHttpBinding_IGameWebService_loadUserNetwork;
            struct  // BasicHttpBinding_IGameWebService_loadUserNetwork_NR
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserNetwork_NR;
            } BasicHttpBinding_IGameWebService_loadUserNetwork_NR;
            struct  // BasicHttpBinding_IGameWebService_loadUserById
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserById;
            } BasicHttpBinding_IGameWebService_loadUserById;
            struct  // BasicHttpBinding_IGameWebService_changeUserPoints
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_changeUserPoints;
            } BasicHttpBinding_IGameWebService_changeUserPoints;
            struct  // BasicHttpBinding_IGameWebService_changeMoodState
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_changeMoodState;
            } BasicHttpBinding_IGameWebService_changeMoodState;
            struct  // BasicHttpBinding_IGameWebService_doNegociationGameComplete
            {
                WS_PARAMETER_DESCRIPTION params[7];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_doNegociationGameComplete;
            } BasicHttpBinding_IGameWebService_doNegociationGameComplete;
            struct  // BasicHttpBinding_IGameWebService_getDictionarys
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_getDictionarys;
            } BasicHttpBinding_IGameWebService_getDictionarys;
            WS_OPERATION_DESCRIPTION* operations[8];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } BasicHttpBinding_IGameWebService;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // BasicHttpBinding_IGameWebService
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } BasicHttpBinding_IGameWebService;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING IGameWebService_login_InputMessageactionName;  // http://tempuri.org/IGameWebService/login
            WS_XML_STRING IGameWebService_login_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loginResponse
            WS_XML_STRING IGameWebService_loadUserNetwork_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork
            WS_XML_STRING IGameWebService_loadUserNetwork_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetworkResponse
            WS_XML_STRING IGameWebService_loadUserNetwork_NR_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_NR
            WS_XML_STRING IGameWebService_loadUserNetwork_NR_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse
            WS_XML_STRING IGameWebService_loadUserById_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserById
            WS_XML_STRING IGameWebService_loadUserById_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserByIdResponse
            WS_XML_STRING IGameWebService_changeUserPoints_InputMessageactionName;  // http://tempuri.org/IGameWebService/changeUserPoints
            WS_XML_STRING IGameWebService_changeUserPoints_OutputMessageactionName;  // http://tempuri.org/IGameWebService/changeUserPointsResponse
            WS_XML_STRING IGameWebService_changeMoodState_InputMessageactionName;  // http://tempuri.org/IGameWebService/changeMoodState
            WS_XML_STRING IGameWebService_changeMoodState_OutputMessageactionName;  // http://tempuri.org/IGameWebService/changeMoodStateResponse
            WS_XML_STRING IGameWebService_doNegociationGameComplete_InputMessageactionName;  // http://tempuri.org/IGameWebService/doNegociationGameComplete
            WS_XML_STRING IGameWebService_doNegociationGameComplete_OutputMessageactionName;  // http://tempuri.org/IGameWebService/doNegociationGameCompleteResponse
            WS_XML_STRING IGameWebService_getDictionarys_InputMessageactionName;  // http://tempuri.org/IGameWebService/getDictionarys
            WS_XML_STRING IGameWebService_getDictionarys_OutputMessageactionName;  // http://tempuri.org/IGameWebService/getDictionarysResponse
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


typedef struct BasicHttpBinding_IGameWebService_loginParamStruct 
{
    WCHAR** username;
    WCHAR** password;
    WCHAR** securityPass;
    int* loginResult;
} BasicHttpBinding_IGameWebService_loginParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loginOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loginCallback _operation = (BasicHttpBinding_IGameWebService_loginCallback)_callback;
    BasicHttpBinding_IGameWebService_loginParamStruct *_stack =(BasicHttpBinding_IGameWebService_loginParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->username),
        *(_stack->password),
        *(_stack->securityPass),
        (_stack->loginResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct 
{
    int* idUser;
    WCHAR** securityPass;
    unsigned int* loadUserNetworkResultCount;
    UserType*** loadUserNetworkResult;
} BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserNetworkOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserNetworkCallback _operation = (BasicHttpBinding_IGameWebService_loadUserNetworkCallback)_callback;
    BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->idUser),
        *(_stack->securityPass),
        _stack->loadUserNetworkResultCount,
        (_stack->loadUserNetworkResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct 
{
    int* idUser;
    WCHAR** securityPass;
    int* loadUserNetwork_NRResult;
} BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserNetwork_NROperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserNetwork_NRCallback _operation = (BasicHttpBinding_IGameWebService_loadUserNetwork_NRCallback)_callback;
    BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->idUser),
        *(_stack->securityPass),
        (_stack->loadUserNetwork_NRResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserByIdParamStruct 
{
    int* id;
    WCHAR** securityPass;
    UserType** loadUserByIdResult;
} BasicHttpBinding_IGameWebService_loadUserByIdParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserByIdOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserByIdCallback _operation = (BasicHttpBinding_IGameWebService_loadUserByIdCallback)_callback;
    BasicHttpBinding_IGameWebService_loadUserByIdParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserByIdParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        *(_stack->securityPass),
        (_stack->loadUserByIdResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_changeUserPointsParamStruct 
{
    int* id;
    int* pointsToAdd;
    WCHAR** securityPass;
    BOOL* changeUserPointsResult;
} BasicHttpBinding_IGameWebService_changeUserPointsParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_changeUserPointsOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_changeUserPointsCallback _operation = (BasicHttpBinding_IGameWebService_changeUserPointsCallback)_callback;
    BasicHttpBinding_IGameWebService_changeUserPointsParamStruct *_stack =(BasicHttpBinding_IGameWebService_changeUserPointsParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        *(_stack->pointsToAdd),
        *(_stack->securityPass),
        (_stack->changeUserPointsResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_changeMoodStateParamStruct 
{
    int* idUser;
    int* mood;
    WCHAR** securityPass;
    BOOL* changeMoodStateResult;
} BasicHttpBinding_IGameWebService_changeMoodStateParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_changeMoodStateOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_changeMoodStateCallback _operation = (BasicHttpBinding_IGameWebService_changeMoodStateCallback)_callback;
    BasicHttpBinding_IGameWebService_changeMoodStateParamStruct *_stack =(BasicHttpBinding_IGameWebService_changeMoodStateParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->idUser),
        *(_stack->mood),
        *(_stack->securityPass),
        (_stack->changeMoodStateResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_doNegociationGameCompleteParamStruct 
{
    int* userId_ONPLAY;
    int* UserIdB;
    int* idGame;
    int* difficulty;
    WCHAR** securityPass;
    unsigned int* doNegociationGameCompleteResultCount;
    UserType*** doNegociationGameCompleteResult;
} BasicHttpBinding_IGameWebService_doNegociationGameCompleteParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_doNegociationGameCompleteOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_doNegociationGameCompleteCallback _operation = (BasicHttpBinding_IGameWebService_doNegociationGameCompleteCallback)_callback;
    BasicHttpBinding_IGameWebService_doNegociationGameCompleteParamStruct *_stack =(BasicHttpBinding_IGameWebService_doNegociationGameCompleteParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->userId_ONPLAY),
        *(_stack->UserIdB),
        *(_stack->idGame),
        *(_stack->difficulty),
        *(_stack->securityPass),
        _stack->doNegociationGameCompleteResultCount,
        (_stack->doNegociationGameCompleteResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_getDictionarysParamStruct 
{
    WCHAR** securityPass;
    unsigned int* getDictionarysResultCount;
    Dict*** getDictionarysResult;
} BasicHttpBinding_IGameWebService_getDictionarysParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_getDictionarysOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_getDictionarysCallback _operation = (BasicHttpBinding_IGameWebService_getDictionarysCallback)_callback;
    BasicHttpBinding_IGameWebService_getDictionarysParamStruct *_stack =(BasicHttpBinding_IGameWebService_getDictionarysParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->securityPass),
        _stack->getDictionarysResultCount,
        (_stack->getDictionarysResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    {  // messages
        {  // message description for IGameWebService_login_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_InputMessageactionName, // http://tempuri.org/IGameWebService/login
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.login, 
        },    // message description for IGameWebService_login_InputMessage
        {  // message description for IGameWebService_login_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_OutputMessageactionName, // http://tempuri.org/IGameWebService/loginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loginResponse, 
        },    // message description for IGameWebService_login_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork, 
        },    // message description for IGameWebService_loadUserNetwork_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetworkResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetworkResponse, 
        },    // message description for IGameWebService_loadUserNetwork_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NR
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NR, 
        },    // message description for IGameWebService_loadUserNetwork_NR_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NRResponse, 
        },    // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
        {  // message description for IGameWebService_loadUserById_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserById
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserById, 
        },    // message description for IGameWebService_loadUserById_InputMessage
        {  // message description for IGameWebService_loadUserById_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserByIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserByIdResponse, 
        },    // message description for IGameWebService_loadUserById_OutputMessage
        {  // message description for IGameWebService_changeUserPoints_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeUserPoints_InputMessageactionName, // http://tempuri.org/IGameWebService/changeUserPoints
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeUserPoints, 
        },    // message description for IGameWebService_changeUserPoints_InputMessage
        {  // message description for IGameWebService_changeUserPoints_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeUserPoints_OutputMessageactionName, // http://tempuri.org/IGameWebService/changeUserPointsResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeUserPointsResponse, 
        },    // message description for IGameWebService_changeUserPoints_OutputMessage
        {  // message description for IGameWebService_changeMoodState_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeMoodState_InputMessageactionName, // http://tempuri.org/IGameWebService/changeMoodState
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeMoodState, 
        },    // message description for IGameWebService_changeMoodState_InputMessage
        {  // message description for IGameWebService_changeMoodState_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeMoodState_OutputMessageactionName, // http://tempuri.org/IGameWebService/changeMoodStateResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeMoodStateResponse, 
        },    // message description for IGameWebService_changeMoodState_OutputMessage
        {  // message description for IGameWebService_doNegociationGameComplete_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_doNegociationGameComplete_InputMessageactionName, // http://tempuri.org/IGameWebService/doNegociationGameComplete
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.doNegociationGameComplete, 
        },    // message description for IGameWebService_doNegociationGameComplete_InputMessage
        {  // message description for IGameWebService_doNegociationGameComplete_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_doNegociationGameComplete_OutputMessageactionName, // http://tempuri.org/IGameWebService/doNegociationGameCompleteResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.doNegociationGameCompleteResponse, 
        },    // message description for IGameWebService_doNegociationGameComplete_OutputMessage
        {  // message description for IGameWebService_getDictionarys_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_getDictionarys_InputMessageactionName, // http://tempuri.org/IGameWebService/getDictionarys
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getDictionarys, 
        },    // message description for IGameWebService_getDictionarys_InputMessage
        {  // message description for IGameWebService_getDictionarys_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_getDictionarys_OutputMessageactionName, // http://tempuri.org/IGameWebService/getDictionarysResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getDictionarysResponse, 
        },    // message description for IGameWebService_getDictionarys_OutputMessage
    },  // end of messages 
    {  // contracts
        {  // BasicHttpBinding_IGameWebService,
            {  // BasicHttpBinding_IGameWebService_login
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_login
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_login
                {  // operation description for BasicHttpBinding_IGameWebService_login
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_login_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_login_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_login.params,
                    BasicHttpBinding_IGameWebService_loginOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_login
            },  // BasicHttpBinding_IGameWebService_login
            {  // BasicHttpBinding_IGameWebService_loadUserNetwork
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserNetwork
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork.params,
                    BasicHttpBinding_IGameWebService_loadUserNetworkOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserNetwork
            },  // BasicHttpBinding_IGameWebService_loadUserNetwork
            {  // BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_NR_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_NR_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_NR.params,
                    BasicHttpBinding_IGameWebService_loadUserNetwork_NROperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
            },  // BasicHttpBinding_IGameWebService_loadUserNetwork_NR
            {  // BasicHttpBinding_IGameWebService_loadUserById
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserById
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserById
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserById
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserById_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserById_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserById.params,
                    BasicHttpBinding_IGameWebService_loadUserByIdOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserById
            },  // BasicHttpBinding_IGameWebService_loadUserById
            {  // BasicHttpBinding_IGameWebService_changeUserPoints
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_changeUserPoints
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_changeUserPoints
                {  // operation description for BasicHttpBinding_IGameWebService_changeUserPoints
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_changeUserPoints_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_changeUserPoints_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_changeUserPoints.params,
                    BasicHttpBinding_IGameWebService_changeUserPointsOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_changeUserPoints
            },  // BasicHttpBinding_IGameWebService_changeUserPoints
            {  // BasicHttpBinding_IGameWebService_changeMoodState
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_changeMoodState
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_changeMoodState
                {  // operation description for BasicHttpBinding_IGameWebService_changeMoodState
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_changeMoodState_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_changeMoodState_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_changeMoodState.params,
                    BasicHttpBinding_IGameWebService_changeMoodStateOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_changeMoodState
            },  // BasicHttpBinding_IGameWebService_changeMoodState
            {  // BasicHttpBinding_IGameWebService_doNegociationGameComplete
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_doNegociationGameComplete
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)3, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)4, (USHORT)-1},
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_doNegociationGameComplete
                {  // operation description for BasicHttpBinding_IGameWebService_doNegociationGameComplete
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_doNegociationGameComplete_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_doNegociationGameComplete_OutputMessage, 
                    0,
                    0,
                    7,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_doNegociationGameComplete.params,
                    BasicHttpBinding_IGameWebService_doNegociationGameCompleteOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_doNegociationGameComplete
            },  // BasicHttpBinding_IGameWebService_doNegociationGameComplete
            {  // BasicHttpBinding_IGameWebService_getDictionarys
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_getDictionarys
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_getDictionarys
                {  // operation description for BasicHttpBinding_IGameWebService_getDictionarys
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_getDictionarys_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_getDictionarys_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_getDictionarys.params,
                    BasicHttpBinding_IGameWebService_getDictionarysOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_getDictionarys
            },  // BasicHttpBinding_IGameWebService_getDictionarys
            {  // array of operations for BasicHttpBinding_IGameWebService
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_login.BasicHttpBinding_IGameWebService_login,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork.BasicHttpBinding_IGameWebService_loadUserNetwork,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_NR.BasicHttpBinding_IGameWebService_loadUserNetwork_NR,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserById.BasicHttpBinding_IGameWebService_loadUserById,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_changeUserPoints.BasicHttpBinding_IGameWebService_changeUserPoints,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_changeMoodState.BasicHttpBinding_IGameWebService_changeMoodState,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_doNegociationGameComplete.BasicHttpBinding_IGameWebService_doNegociationGameComplete,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_getDictionarys.BasicHttpBinding_IGameWebService_getDictionarys,
            },  // array of operations for BasicHttpBinding_IGameWebService
            {  // contract description for BasicHttpBinding_IGameWebService
            8,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.operations,
            },  // end of contract description for BasicHttpBinding_IGameWebService
        },  // BasicHttpBinding_IGameWebService
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.envelopeVersion),
                },
            },
        },   // end of BasicHttpBinding_IGameWebService,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/login",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loginResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetworkResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_NR",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserById",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserByIdResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/changeUserPoints",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/changeUserPointsResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/changeMoodState",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/changeMoodStateResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/doNegociationGameComplete",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/doNegociationGameCompleteResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/getDictionarys",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/getDictionarysResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 15),
        },  // end of xmlStrings
        
        {  // tempuri_org_wsdldictionary
          // 5d1f5dc6-9fdf-4bed-b17b-417a47585389 
        { 0x5d1f5dc6, 0x9fdf, 0x4bed, { 0xb1, 0x7b, 0x41,0x7a, 0x47, 0x58, 0x53, 0x89 } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        16,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: BasicHttpBinding_IGameWebService_login
HRESULT WINAPI BasicHttpBinding_IGameWebService_login(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* username, 
    _In_opt_z_ WCHAR* password, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ int* loginResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &username;
    _argList[1] = &password;
    _argList[2] = &securityPass;
    _argList[3] = &loginResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_login.BasicHttpBinding_IGameWebService_login,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserNetwork
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserNetwork(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int idUser, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ unsigned int* loadUserNetworkResultCount, 
    _Outptr_opt_result_buffer_(*loadUserNetworkResultCount) UserType*** loadUserNetworkResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &idUser;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserNetworkResultCount;
    _argList[3] = &loadUserNetworkResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork.BasicHttpBinding_IGameWebService_loadUserNetwork,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserNetwork_NR
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserNetwork_NR(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int idUser, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ int* loadUserNetwork_NRResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &idUser;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserNetwork_NRResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_NR.BasicHttpBinding_IGameWebService_loadUserNetwork_NR,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserById
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserById(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id, 
    _In_opt_z_ WCHAR* securityPass, 
    _Outptr_opt_ UserType** loadUserByIdResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &id;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserByIdResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserById.BasicHttpBinding_IGameWebService_loadUserById,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_changeUserPoints
HRESULT WINAPI BasicHttpBinding_IGameWebService_changeUserPoints(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id, 
    _In_ int pointsToAdd, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ BOOL* changeUserPointsResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &id;
    _argList[1] = &pointsToAdd;
    _argList[2] = &securityPass;
    _argList[3] = &changeUserPointsResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_changeUserPoints.BasicHttpBinding_IGameWebService_changeUserPoints,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_changeMoodState
HRESULT WINAPI BasicHttpBinding_IGameWebService_changeMoodState(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int idUser, 
    _In_ int mood, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ BOOL* changeMoodStateResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &idUser;
    _argList[1] = &mood;
    _argList[2] = &securityPass;
    _argList[3] = &changeMoodStateResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_changeMoodState.BasicHttpBinding_IGameWebService_changeMoodState,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_doNegociationGameComplete
HRESULT WINAPI BasicHttpBinding_IGameWebService_doNegociationGameComplete(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int userId_ONPLAY, 
    _In_ int UserIdB, 
    _In_ int idGame, 
    _In_ int difficulty, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ unsigned int* doNegociationGameCompleteResultCount, 
    _Outptr_opt_result_buffer_(*doNegociationGameCompleteResultCount) UserType*** doNegociationGameCompleteResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[7]; 
    _argList[0] = &userId_ONPLAY;
    _argList[1] = &UserIdB;
    _argList[2] = &idGame;
    _argList[3] = &difficulty;
    _argList[4] = &securityPass;
    _argList[5] = &doNegociationGameCompleteResultCount;
    _argList[6] = &doNegociationGameCompleteResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_doNegociationGameComplete.BasicHttpBinding_IGameWebService_doNegociationGameComplete,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_getDictionarys
HRESULT WINAPI BasicHttpBinding_IGameWebService_getDictionarys(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ unsigned int* getDictionarysResultCount, 
    _Outptr_opt_result_buffer_(*getDictionarysResultCount) Dict*** getDictionarysResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &securityPass;
    _argList[1] = &getDictionarysResultCount;
    _argList[2] = &getDictionarysResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_getDictionarys.BasicHttpBinding_IGameWebService_getDictionarys,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {  // messages
        {  // message description for IGameWebService_login_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_InputMessageactionName, // http://tempuri.org/IGameWebService/login
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.login, 
        },    // message description for IGameWebService_login_InputMessage
        {  // message description for IGameWebService_login_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_OutputMessageactionName, // http://tempuri.org/IGameWebService/loginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loginResponse, 
        },    // message description for IGameWebService_login_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork, 
        },    // message description for IGameWebService_loadUserNetwork_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetworkResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetworkResponse, 
        },    // message description for IGameWebService_loadUserNetwork_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NR
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NR, 
        },    // message description for IGameWebService_loadUserNetwork_NR_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NRResponse, 
        },    // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
        {  // message description for IGameWebService_loadUserById_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserById
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserById, 
        },    // message description for IGameWebService_loadUserById_InputMessage
        {  // message description for IGameWebService_loadUserById_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserByIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserByIdResponse, 
        },    // message description for IGameWebService_loadUserById_OutputMessage
        {  // message description for IGameWebService_changeUserPoints_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeUserPoints_InputMessageactionName, // http://tempuri.org/IGameWebService/changeUserPoints
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeUserPoints, 
        },    // message description for IGameWebService_changeUserPoints_InputMessage
        {  // message description for IGameWebService_changeUserPoints_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeUserPoints_OutputMessageactionName, // http://tempuri.org/IGameWebService/changeUserPointsResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeUserPointsResponse, 
        },    // message description for IGameWebService_changeUserPoints_OutputMessage
        {  // message description for IGameWebService_changeMoodState_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeMoodState_InputMessageactionName, // http://tempuri.org/IGameWebService/changeMoodState
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeMoodState, 
        },    // message description for IGameWebService_changeMoodState_InputMessage
        {  // message description for IGameWebService_changeMoodState_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_changeMoodState_OutputMessageactionName, // http://tempuri.org/IGameWebService/changeMoodStateResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.changeMoodStateResponse, 
        },    // message description for IGameWebService_changeMoodState_OutputMessage
        {  // message description for IGameWebService_doNegociationGameComplete_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_doNegociationGameComplete_InputMessageactionName, // http://tempuri.org/IGameWebService/doNegociationGameComplete
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.doNegociationGameComplete, 
        },    // message description for IGameWebService_doNegociationGameComplete_InputMessage
        {  // message description for IGameWebService_doNegociationGameComplete_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_doNegociationGameComplete_OutputMessageactionName, // http://tempuri.org/IGameWebService/doNegociationGameCompleteResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.doNegociationGameCompleteResponse, 
        },    // message description for IGameWebService_doNegociationGameComplete_OutputMessage
        {  // message description for IGameWebService_getDictionarys_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_getDictionarys_InputMessageactionName, // http://tempuri.org/IGameWebService/getDictionarys
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getDictionarys, 
        },    // message description for IGameWebService_getDictionarys_InputMessage
        {  // message description for IGameWebService_getDictionarys_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_getDictionarys_OutputMessageactionName, // http://tempuri.org/IGameWebService/getDictionarysResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getDictionarysResponse, 
        },    // message description for IGameWebService_getDictionarys_OutputMessage
    },  // messages
    {  // contracts
        {  // BasicHttpBinding_IGameWebService
            8,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.operations,
        },  // end of BasicHttpBinding_IGameWebService
    },  // contracts
    {  // policies
        {  // template description for BasicHttpBinding_IGameWebService
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _tempuri_org_wsdl

HRESULT BasicHttpBinding_IGameWebService_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService),
        _serviceProxy,
        error);
}

HRESULT BasicHttpBinding_IGameWebService_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct BasicHttpBinding_IGameWebServiceFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.BasicHttpBinding_IGameWebService;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService),
        serviceEndpoint,
        error);
}
