
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "System.xsd.h"
#include "GameWS.xsd.h"
#include "DataModel.Model.xsd.h"
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION IGameWebService_login_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_login_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_2_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_2_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_3_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_3_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_NR_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserNetwork_NR_OutputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserById_InputMessage;
        WS_MESSAGE_DESCRIPTION IGameWebService_loadUserById_OutputMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // BasicHttpBinding_IGameWebService
        {
            struct  // BasicHttpBinding_IGameWebService_login
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_login;
            } BasicHttpBinding_IGameWebService_login;
            struct  // BasicHttpBinding_IGameWebService_loadUserNetwork
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserNetwork;
            } BasicHttpBinding_IGameWebService_loadUserNetwork;
            struct  // BasicHttpBinding_IGameWebService_loadUserNetwork_2
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserNetwork_2;
            } BasicHttpBinding_IGameWebService_loadUserNetwork_2;
            struct  // BasicHttpBinding_IGameWebService_loadUserNetwork_3
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserNetwork_3;
            } BasicHttpBinding_IGameWebService_loadUserNetwork_3;
            struct  // BasicHttpBinding_IGameWebService_loadUserNetwork_NR
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserNetwork_NR;
            } BasicHttpBinding_IGameWebService_loadUserNetwork_NR;
            struct  // BasicHttpBinding_IGameWebService_loadUserById
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IGameWebService_loadUserById;
            } BasicHttpBinding_IGameWebService_loadUserById;
            WS_OPERATION_DESCRIPTION* operations[6];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } BasicHttpBinding_IGameWebService;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // BasicHttpBinding_IGameWebService
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } BasicHttpBinding_IGameWebService;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING IGameWebService_login_InputMessageactionName;  // http://tempuri.org/IGameWebService/login
            WS_XML_STRING IGameWebService_login_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loginResponse
            WS_XML_STRING IGameWebService_loadUserNetwork_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork
            WS_XML_STRING IGameWebService_loadUserNetwork_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetworkResponse
            WS_XML_STRING IGameWebService_loadUserNetwork_2_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_2
            WS_XML_STRING IGameWebService_loadUserNetwork_2_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_2Response
            WS_XML_STRING IGameWebService_loadUserNetwork_3_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_3
            WS_XML_STRING IGameWebService_loadUserNetwork_3_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_3Response
            WS_XML_STRING IGameWebService_loadUserNetwork_NR_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_NR
            WS_XML_STRING IGameWebService_loadUserNetwork_NR_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse
            WS_XML_STRING IGameWebService_loadUserById_InputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserById
            WS_XML_STRING IGameWebService_loadUserById_OutputMessageactionName;  // http://tempuri.org/IGameWebService/loadUserByIdResponse
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


typedef struct BasicHttpBinding_IGameWebService_loginParamStruct 
{
    WCHAR** username;
    WCHAR** password;
    WCHAR** securityPass;
    int* loginResult;
} BasicHttpBinding_IGameWebService_loginParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loginOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loginCallback _operation = (BasicHttpBinding_IGameWebService_loginCallback)_callback;
    BasicHttpBinding_IGameWebService_loginParamStruct *_stack =(BasicHttpBinding_IGameWebService_loginParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->username),
        *(_stack->password),
        *(_stack->securityPass),
        (_stack->loginResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct 
{
    int* idUser;
    WCHAR** securityPass;
    unsigned int* loadUserNetworkResultCount;
    UserType*** loadUserNetworkResult;
} BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserNetworkOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserNetworkCallback _operation = (BasicHttpBinding_IGameWebService_loadUserNetworkCallback)_callback;
    BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserNetworkParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->idUser),
        *(_stack->securityPass),
        _stack->loadUserNetworkResultCount,
        (_stack->loadUserNetworkResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserNetwork_2ParamStruct 
{
    int* idUser;
    WCHAR** securityPass;
    unsigned int* loadUserNetwork_2ResultCount;
    User*** loadUserNetwork_2Result;
} BasicHttpBinding_IGameWebService_loadUserNetwork_2ParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserNetwork_2OperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserNetwork_2Callback _operation = (BasicHttpBinding_IGameWebService_loadUserNetwork_2Callback)_callback;
    BasicHttpBinding_IGameWebService_loadUserNetwork_2ParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserNetwork_2ParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->idUser),
        *(_stack->securityPass),
        _stack->loadUserNetwork_2ResultCount,
        (_stack->loadUserNetwork_2Result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserNetwork_3ParamStruct 
{
    int* idUser;
    WCHAR** securityPass;
    WCHAR** loadUserNetwork_3Result;
} BasicHttpBinding_IGameWebService_loadUserNetwork_3ParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserNetwork_3OperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserNetwork_3Callback _operation = (BasicHttpBinding_IGameWebService_loadUserNetwork_3Callback)_callback;
    BasicHttpBinding_IGameWebService_loadUserNetwork_3ParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserNetwork_3ParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->idUser),
        *(_stack->securityPass),
        (_stack->loadUserNetwork_3Result),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct 
{
    int* idUser;
    WCHAR** securityPass;
    int* loadUserNetwork_NRResult;
} BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserNetwork_NROperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserNetwork_NRCallback _operation = (BasicHttpBinding_IGameWebService_loadUserNetwork_NRCallback)_callback;
    BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserNetwork_NRParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->idUser),
        *(_stack->securityPass),
        (_stack->loadUserNetwork_NRResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IGameWebService_loadUserByIdParamStruct 
{
    int* id;
    WCHAR** securityPass;
    UserType** loadUserByIdResult;
} BasicHttpBinding_IGameWebService_loadUserByIdParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IGameWebService_loadUserByIdOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IGameWebService_loadUserByIdCallback _operation = (BasicHttpBinding_IGameWebService_loadUserByIdCallback)_callback;
    BasicHttpBinding_IGameWebService_loadUserByIdParamStruct *_stack =(BasicHttpBinding_IGameWebService_loadUserByIdParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        *(_stack->securityPass),
        (_stack->loadUserByIdResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    {  // messages
        {  // message description for IGameWebService_login_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_InputMessageactionName, // http://tempuri.org/IGameWebService/login
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.login, 
        },    // message description for IGameWebService_login_InputMessage
        {  // message description for IGameWebService_login_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_OutputMessageactionName, // http://tempuri.org/IGameWebService/loginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loginResponse, 
        },    // message description for IGameWebService_login_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork, 
        },    // message description for IGameWebService_loadUserNetwork_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetworkResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetworkResponse, 
        },    // message description for IGameWebService_loadUserNetwork_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_2_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_2_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_2
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_2, 
        },    // message description for IGameWebService_loadUserNetwork_2_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_2_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_2_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_2Response
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_2Response, 
        },    // message description for IGameWebService_loadUserNetwork_2_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_3_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_3_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_3
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_3, 
        },    // message description for IGameWebService_loadUserNetwork_3_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_3_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_3_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_3Response
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_3Response, 
        },    // message description for IGameWebService_loadUserNetwork_3_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NR
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NR, 
        },    // message description for IGameWebService_loadUserNetwork_NR_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NRResponse, 
        },    // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
        {  // message description for IGameWebService_loadUserById_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserById
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserById, 
        },    // message description for IGameWebService_loadUserById_InputMessage
        {  // message description for IGameWebService_loadUserById_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserByIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserByIdResponse, 
        },    // message description for IGameWebService_loadUserById_OutputMessage
    },  // end of messages 
    {  // contracts
        {  // BasicHttpBinding_IGameWebService,
            {  // BasicHttpBinding_IGameWebService_login
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_login
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_login
                {  // operation description for BasicHttpBinding_IGameWebService_login
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_login_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_login_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_login.params,
                    BasicHttpBinding_IGameWebService_loginOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_login
            },  // BasicHttpBinding_IGameWebService_login
            {  // BasicHttpBinding_IGameWebService_loadUserNetwork
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserNetwork
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork.params,
                    BasicHttpBinding_IGameWebService_loadUserNetworkOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserNetwork
            },  // BasicHttpBinding_IGameWebService_loadUserNetwork
            {  // BasicHttpBinding_IGameWebService_loadUserNetwork_2
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_2
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_2
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_2
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_2_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_2_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_2.params,
                    BasicHttpBinding_IGameWebService_loadUserNetwork_2OperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_2
            },  // BasicHttpBinding_IGameWebService_loadUserNetwork_2
            {  // BasicHttpBinding_IGameWebService_loadUserNetwork_3
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_3
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_3
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_3
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_3_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_3_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_3.params,
                    BasicHttpBinding_IGameWebService_loadUserNetwork_3OperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_3
            },  // BasicHttpBinding_IGameWebService_loadUserNetwork_3
            {  // BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_NR_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserNetwork_NR_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_NR.params,
                    BasicHttpBinding_IGameWebService_loadUserNetwork_NROperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserNetwork_NR
            },  // BasicHttpBinding_IGameWebService_loadUserNetwork_NR
            {  // BasicHttpBinding_IGameWebService_loadUserById
                {  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserById
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IGameWebService_loadUserById
                {  // operation description for BasicHttpBinding_IGameWebService_loadUserById
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserById_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IGameWebService_loadUserById_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserById.params,
                    BasicHttpBinding_IGameWebService_loadUserByIdOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IGameWebService_loadUserById
            },  // BasicHttpBinding_IGameWebService_loadUserById
            {  // array of operations for BasicHttpBinding_IGameWebService
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_login.BasicHttpBinding_IGameWebService_login,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork.BasicHttpBinding_IGameWebService_loadUserNetwork,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_2.BasicHttpBinding_IGameWebService_loadUserNetwork_2,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_3.BasicHttpBinding_IGameWebService_loadUserNetwork_3,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_NR.BasicHttpBinding_IGameWebService_loadUserNetwork_NR,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserById.BasicHttpBinding_IGameWebService_loadUserById,
            },  // array of operations for BasicHttpBinding_IGameWebService
            {  // contract description for BasicHttpBinding_IGameWebService
            6,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.operations,
            },  // end of contract description for BasicHttpBinding_IGameWebService
        },  // BasicHttpBinding_IGameWebService
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.envelopeVersion),
                },
            },
        },   // end of BasicHttpBinding_IGameWebService,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/login",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loginResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetworkResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_2",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_2Response",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_3",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_3Response",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_NR",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserById",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IGameWebService/loadUserByIdResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 11),
        },  // end of xmlStrings
        
        {  // tempuri_org_wsdldictionary
          // 58199115-c879-427b-b7cc-2b3ebedc0840 
        { 0x58199115, 0xc879, 0x427b, { 0xb7, 0xcc, 0x2b,0x3e, 0xbe, 0xdc, 0x08, 0x40 } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        12,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: BasicHttpBinding_IGameWebService_login
HRESULT WINAPI BasicHttpBinding_IGameWebService_login(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* username, 
    _In_opt_z_ WCHAR* password, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ int* loginResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &username;
    _argList[1] = &password;
    _argList[2] = &securityPass;
    _argList[3] = &loginResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_login.BasicHttpBinding_IGameWebService_login,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserNetwork
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserNetwork(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int idUser, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ unsigned int* loadUserNetworkResultCount, 
    _Outptr_opt_result_buffer_(*loadUserNetworkResultCount) UserType*** loadUserNetworkResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &idUser;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserNetworkResultCount;
    _argList[3] = &loadUserNetworkResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork.BasicHttpBinding_IGameWebService_loadUserNetwork,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserNetwork_2
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserNetwork_2(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int idUser, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ unsigned int* loadUserNetwork_2ResultCount, 
    _Outptr_opt_result_buffer_(*loadUserNetwork_2ResultCount) User*** loadUserNetwork_2Result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &idUser;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserNetwork_2ResultCount;
    _argList[3] = &loadUserNetwork_2Result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_2.BasicHttpBinding_IGameWebService_loadUserNetwork_2,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserNetwork_3
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserNetwork_3(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int idUser, 
    _In_opt_z_ WCHAR* securityPass, 
    _Outptr_opt_result_z_ WCHAR** loadUserNetwork_3Result, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &idUser;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserNetwork_3Result;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_3.BasicHttpBinding_IGameWebService_loadUserNetwork_3,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserNetwork_NR
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserNetwork_NR(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int idUser, 
    _In_opt_z_ WCHAR* securityPass, 
    _Out_ int* loadUserNetwork_NRResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &idUser;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserNetwork_NRResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserNetwork_NR.BasicHttpBinding_IGameWebService_loadUserNetwork_NR,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IGameWebService_loadUserById
HRESULT WINAPI BasicHttpBinding_IGameWebService_loadUserById(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id, 
    _In_opt_z_ WCHAR* securityPass, 
    _Outptr_opt_ UserType** loadUserByIdResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &id;
    _argList[1] = &securityPass;
    _argList[2] = &loadUserByIdResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.BasicHttpBinding_IGameWebService_loadUserById.BasicHttpBinding_IGameWebService_loadUserById,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {  // messages
        {  // message description for IGameWebService_login_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_InputMessageactionName, // http://tempuri.org/IGameWebService/login
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.login, 
        },    // message description for IGameWebService_login_InputMessage
        {  // message description for IGameWebService_login_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_login_OutputMessageactionName, // http://tempuri.org/IGameWebService/loginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loginResponse, 
        },    // message description for IGameWebService_login_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork, 
        },    // message description for IGameWebService_loadUserNetwork_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetworkResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetworkResponse, 
        },    // message description for IGameWebService_loadUserNetwork_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_2_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_2_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_2
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_2, 
        },    // message description for IGameWebService_loadUserNetwork_2_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_2_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_2_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_2Response
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_2Response, 
        },    // message description for IGameWebService_loadUserNetwork_2_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_3_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_3_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_3
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_3, 
        },    // message description for IGameWebService_loadUserNetwork_3_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_3_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_3_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_3Response
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_3Response, 
        },    // message description for IGameWebService_loadUserNetwork_3_OutputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NR
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NR, 
        },    // message description for IGameWebService_loadUserNetwork_NR_InputMessage
        {  // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserNetwork_NR_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserNetwork_NRResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserNetwork_NRResponse, 
        },    // message description for IGameWebService_loadUserNetwork_NR_OutputMessage
        {  // message description for IGameWebService_loadUserById_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_InputMessageactionName, // http://tempuri.org/IGameWebService/loadUserById
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserById, 
        },    // message description for IGameWebService_loadUserById_InputMessage
        {  // message description for IGameWebService_loadUserById_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IGameWebService_loadUserById_OutputMessageactionName, // http://tempuri.org/IGameWebService/loadUserByIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.loadUserByIdResponse, 
        },    // message description for IGameWebService_loadUserById_OutputMessage
    },  // messages
    {  // contracts
        {  // BasicHttpBinding_IGameWebService
            6,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IGameWebService.operations,
        },  // end of BasicHttpBinding_IGameWebService
    },  // contracts
    {  // policies
        {  // template description for BasicHttpBinding_IGameWebService
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IGameWebService.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _tempuri_org_wsdl

HRESULT BasicHttpBinding_IGameWebService_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService),
        _serviceProxy,
        error);
}

HRESULT BasicHttpBinding_IGameWebService_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct BasicHttpBinding_IGameWebServiceFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.BasicHttpBinding_IGameWebService;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IGameWebService),
        serviceEndpoint,
        error);
}
