
// File generated by Wsutil Compiler version 1.0095 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by Wsutil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _login;
//     struct _loginResponse;
//     struct _loadUserNetwork;
//     struct _loadUserNetworkResponse;
//     struct _loadUserNetwork_NR;
//     struct _loadUserNetwork_NRResponse;
//     struct _loadUserById;
//     struct _loadUserByIdResponse;
//     struct _changeUserPoints;
//     struct _changeUserPointsResponse;
//     struct _changeMoodState;
//     struct _changeMoodStateResponse;
//     struct _doNegociationGameComplete;
//     struct _doNegociationGameCompleteResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "GameWS.xsd.h"

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: n/a
typedef struct _login 
{
    WCHAR* username; // optional
    WCHAR* password; // optional
    WCHAR* securityPass; // optional
} _login;

// typeDescription: n/a
typedef struct _loginResponse 
{
    int loginResult;
} _loginResponse;

// typeDescription: n/a
typedef struct _loadUserNetwork 
{
    int idUser;
    WCHAR* securityPass; // optional
} _loadUserNetwork;

// typeDescription: n/a
typedef struct _loadUserNetworkResponse 
{
    unsigned int loadUserNetworkResultCount;
    _Field_size_opt_(loadUserNetworkResultCount)struct UserType** loadUserNetworkResult; // optional
} _loadUserNetworkResponse;

// typeDescription: n/a
typedef struct _loadUserNetwork_NR 
{
    int idUser;
    WCHAR* securityPass; // optional
} _loadUserNetwork_NR;

// typeDescription: n/a
typedef struct _loadUserNetwork_NRResponse 
{
    int loadUserNetwork_NRResult;
} _loadUserNetwork_NRResponse;

// typeDescription: n/a
typedef struct _loadUserById 
{
    int id;
    WCHAR* securityPass; // optional
} _loadUserById;

// typeDescription: n/a
typedef struct _loadUserByIdResponse 
{
    struct UserType* loadUserByIdResult; // optional
} _loadUserByIdResponse;

// typeDescription: n/a
typedef struct _changeUserPoints 
{
    int id;
    int pointsToAdd;
    WCHAR* securityPass; // optional
} _changeUserPoints;

// typeDescription: n/a
typedef struct _changeUserPointsResponse 
{
    BOOL changeUserPointsResult;
} _changeUserPointsResponse;

// typeDescription: n/a
typedef struct _changeMoodState 
{
    int idUser;
    int mood;
    WCHAR* securityPass; // optional
} _changeMoodState;

// typeDescription: n/a
typedef struct _changeMoodStateResponse 
{
    BOOL changeMoodStateResult;
} _changeMoodStateResponse;

// typeDescription: n/a
typedef struct _doNegociationGameComplete 
{
    int userId_ONPLAY;
    int UserIdB;
    int idGame;
    int difficulty;
    WCHAR* securityPass; // optional
} _doNegociationGameComplete;

// typeDescription: n/a
typedef struct _doNegociationGameCompleteResponse 
{
    struct UserType* doNegociationGameCompleteResult; // optional
} _doNegociationGameCompleteResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_xsd
{
    struct // globalElements
    {
        // xml element: login ("http://tempuri.org/")
        // c type: _login
        // elementDescription: tempuri_org_xsd.globalElements.login
        WS_ELEMENT_DESCRIPTION login;
        
        // xml element: loginResponse ("http://tempuri.org/")
        // c type: _loginResponse
        // elementDescription: tempuri_org_xsd.globalElements.loginResponse
        WS_ELEMENT_DESCRIPTION loginResponse;
        
        // xml element: loadUserNetwork ("http://tempuri.org/")
        // c type: _loadUserNetwork
        // elementDescription: tempuri_org_xsd.globalElements.loadUserNetwork
        WS_ELEMENT_DESCRIPTION loadUserNetwork;
        
        // xml element: loadUserNetworkResponse ("http://tempuri.org/")
        // c type: _loadUserNetworkResponse
        // elementDescription: tempuri_org_xsd.globalElements.loadUserNetworkResponse
        WS_ELEMENT_DESCRIPTION loadUserNetworkResponse;
        
        // xml element: loadUserNetwork_NR ("http://tempuri.org/")
        // c type: _loadUserNetwork_NR
        // elementDescription: tempuri_org_xsd.globalElements.loadUserNetwork_NR
        WS_ELEMENT_DESCRIPTION loadUserNetwork_NR;
        
        // xml element: loadUserNetwork_NRResponse ("http://tempuri.org/")
        // c type: _loadUserNetwork_NRResponse
        // elementDescription: tempuri_org_xsd.globalElements.loadUserNetwork_NRResponse
        WS_ELEMENT_DESCRIPTION loadUserNetwork_NRResponse;
        
        // xml element: loadUserById ("http://tempuri.org/")
        // c type: _loadUserById
        // elementDescription: tempuri_org_xsd.globalElements.loadUserById
        WS_ELEMENT_DESCRIPTION loadUserById;
        
        // xml element: loadUserByIdResponse ("http://tempuri.org/")
        // c type: _loadUserByIdResponse
        // elementDescription: tempuri_org_xsd.globalElements.loadUserByIdResponse
        WS_ELEMENT_DESCRIPTION loadUserByIdResponse;
        
        // xml element: changeUserPoints ("http://tempuri.org/")
        // c type: _changeUserPoints
        // elementDescription: tempuri_org_xsd.globalElements.changeUserPoints
        WS_ELEMENT_DESCRIPTION changeUserPoints;
        
        // xml element: changeUserPointsResponse ("http://tempuri.org/")
        // c type: _changeUserPointsResponse
        // elementDescription: tempuri_org_xsd.globalElements.changeUserPointsResponse
        WS_ELEMENT_DESCRIPTION changeUserPointsResponse;
        
        // xml element: changeMoodState ("http://tempuri.org/")
        // c type: _changeMoodState
        // elementDescription: tempuri_org_xsd.globalElements.changeMoodState
        WS_ELEMENT_DESCRIPTION changeMoodState;
        
        // xml element: changeMoodStateResponse ("http://tempuri.org/")
        // c type: _changeMoodStateResponse
        // elementDescription: tempuri_org_xsd.globalElements.changeMoodStateResponse
        WS_ELEMENT_DESCRIPTION changeMoodStateResponse;
        
        // xml element: doNegociationGameComplete ("http://tempuri.org/")
        // c type: _doNegociationGameComplete
        // elementDescription: tempuri_org_xsd.globalElements.doNegociationGameComplete
        WS_ELEMENT_DESCRIPTION doNegociationGameComplete;
        
        // xml element: doNegociationGameCompleteResponse ("http://tempuri.org/")
        // c type: _doNegociationGameCompleteResponse
        // elementDescription: tempuri_org_xsd.globalElements.doNegociationGameCompleteResponse
        WS_ELEMENT_DESCRIPTION doNegociationGameCompleteResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION login;
        WS_STRUCT_DESCRIPTION loginResponse;
        WS_STRUCT_DESCRIPTION loadUserNetwork;
        WS_STRUCT_DESCRIPTION loadUserNetworkResponse;
        WS_STRUCT_DESCRIPTION loadUserNetwork_NR;
        WS_STRUCT_DESCRIPTION loadUserNetwork_NRResponse;
        WS_STRUCT_DESCRIPTION loadUserById;
        WS_STRUCT_DESCRIPTION loadUserByIdResponse;
        WS_STRUCT_DESCRIPTION changeUserPoints;
        WS_STRUCT_DESCRIPTION changeUserPointsResponse;
        WS_STRUCT_DESCRIPTION changeMoodState;
        WS_STRUCT_DESCRIPTION changeMoodStateResponse;
        WS_STRUCT_DESCRIPTION doNegociationGameComplete;
        WS_STRUCT_DESCRIPTION doNegociationGameCompleteResponse;
    } externallyReferencedTypes;
} _tempuri_org_xsd;

extern const _tempuri_org_xsd tempuri_org_xsd;

#ifdef __cplusplus
}
#endif

