
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "GameWS.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _login
        {
            WS_FIELD_DESCRIPTION username;
            WS_FIELD_DESCRIPTION password;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loginFields [3]; 
        } _logindescs; // end of _login
        struct  // _loginResponse
        {
            WS_FIELD_DESCRIPTION loginResult;
            WS_FIELD_DESCRIPTION* _loginResponseFields [1]; 
        } _loginResponsedescs; // end of _loginResponse
        struct  // _loadUserNetwork
        {
            WS_FIELD_DESCRIPTION idUser;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserNetworkFields [2]; 
        } _loadUserNetworkdescs; // end of _loadUserNetwork
        struct  // _loadUserNetworkResponse
        {
            WS_FIELD_DESCRIPTION loadUserNetworkResult;
            WS_FIELD_DESCRIPTION* _loadUserNetworkResponseFields [1]; 
        } _loadUserNetworkResponsedescs; // end of _loadUserNetworkResponse
        struct  // _loadUserNetwork_NR
        {
            WS_FIELD_DESCRIPTION idUser;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_NRFields [2]; 
        } _loadUserNetwork_NRdescs; // end of _loadUserNetwork_NR
        struct  // _loadUserNetwork_NRResponse
        {
            WS_FIELD_DESCRIPTION loadUserNetwork_NRResult;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_NRResponseFields [1]; 
        } _loadUserNetwork_NRResponsedescs; // end of _loadUserNetwork_NRResponse
        struct  // _loadUserById
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserByIdFields [2]; 
        } _loadUserByIddescs; // end of _loadUserById
        struct  // _loadUserByIdResponse
        {
            WS_FIELD_DESCRIPTION loadUserByIdResult;
            WS_FIELD_DESCRIPTION* _loadUserByIdResponseFields [1]; 
        } _loadUserByIdResponsedescs; // end of _loadUserByIdResponse
        struct  // _changeUserPoints
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION pointsToAdd;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _changeUserPointsFields [3]; 
        } _changeUserPointsdescs; // end of _changeUserPoints
        struct  // _changeUserPointsResponse
        {
            WS_FIELD_DESCRIPTION changeUserPointsResult;
            WS_FIELD_DESCRIPTION* _changeUserPointsResponseFields [1]; 
        } _changeUserPointsResponsedescs; // end of _changeUserPointsResponse
        struct  // _changeMoodState
        {
            WS_FIELD_DESCRIPTION idUser;
            WS_FIELD_DESCRIPTION mood;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _changeMoodStateFields [3]; 
        } _changeMoodStatedescs; // end of _changeMoodState
        struct  // _changeMoodStateResponse
        {
            WS_FIELD_DESCRIPTION changeMoodStateResult;
            WS_FIELD_DESCRIPTION* _changeMoodStateResponseFields [1]; 
        } _changeMoodStateResponsedescs; // end of _changeMoodStateResponse
        struct  // _doNegociationGameComplete
        {
            WS_FIELD_DESCRIPTION userId_ONPLAY;
            WS_FIELD_DESCRIPTION UserIdB;
            WS_FIELD_DESCRIPTION idGame;
            WS_FIELD_DESCRIPTION difficulty;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _doNegociationGameCompleteFields [5]; 
        } _doNegociationGameCompletedescs; // end of _doNegociationGameComplete
        struct  // _doNegociationGameCompleteResponse
        {
            WS_FIELD_DESCRIPTION doNegociationGameCompleteResult;
            WS_FIELD_DESCRIPTION* _doNegociationGameCompleteResponseFields [1]; 
        } _doNegociationGameCompleteResponsedescs; // end of _doNegociationGameCompleteResponse
    } globalElements;  // end of global elements
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _loginTypeName;  // login
            WS_XML_STRING _loginTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _loginusernameLocalName;  // username
            WS_XML_STRING _loginpasswordLocalName;  // password
            WS_XML_STRING _loginsecurityPassLocalName;  // securityPass
            WS_XML_STRING _loginResponseTypeName;  // loginResponse
            WS_XML_STRING _loginResponseloginResultLocalName;  // loginResult
            WS_XML_STRING _loadUserNetworkTypeName;  // loadUserNetwork
            WS_XML_STRING _loadUserNetworkidUserLocalName;  // idUser
            WS_XML_STRING _loadUserNetworkResponseTypeName;  // loadUserNetworkResponse
            WS_XML_STRING _loadUserNetworkResponseloadUserNetworkResultLocalName;  // UserType
            WS_XML_STRING _loadUserNetworkResponseloadUserNetworkResultNamespace;  // http://schemas.datacontract.org/2004/07/GameWS
            WS_XML_STRING _loadUserNetworkResponseloadUserNetworkResultWrapperName;  // loadUserNetworkResult
            WS_XML_STRING _loadUserNetwork_NRTypeName;  // loadUserNetwork_NR
            WS_XML_STRING _loadUserNetwork_NRResponseTypeName;  // loadUserNetwork_NRResponse
            WS_XML_STRING _loadUserNetwork_NRResponseloadUserNetwork_NRResultLocalName;  // loadUserNetwork_NRResult
            WS_XML_STRING _loadUserByIdTypeName;  // loadUserById
            WS_XML_STRING _loadUserByIdidLocalName;  // id
            WS_XML_STRING _loadUserByIdResponseTypeName;  // loadUserByIdResponse
            WS_XML_STRING _loadUserByIdResponseloadUserByIdResultLocalName;  // loadUserByIdResult
            WS_XML_STRING _changeUserPointsTypeName;  // changeUserPoints
            WS_XML_STRING _changeUserPointspointsToAddLocalName;  // pointsToAdd
            WS_XML_STRING _changeUserPointsResponseTypeName;  // changeUserPointsResponse
            WS_XML_STRING _changeUserPointsResponsechangeUserPointsResultLocalName;  // changeUserPointsResult
            WS_XML_STRING _changeMoodStateTypeName;  // changeMoodState
            WS_XML_STRING _changeMoodStatemoodLocalName;  // mood
            WS_XML_STRING _changeMoodStateResponseTypeName;  // changeMoodStateResponse
            WS_XML_STRING _changeMoodStateResponsechangeMoodStateResultLocalName;  // changeMoodStateResult
            WS_XML_STRING _doNegociationGameCompleteTypeName;  // doNegociationGameComplete
            WS_XML_STRING _doNegociationGameCompleteuserId_ONPLAYLocalName;  // userId_ONPLAY
            WS_XML_STRING _doNegociationGameCompleteUserIdBLocalName;  // UserIdB
            WS_XML_STRING _doNegociationGameCompleteidGameLocalName;  // idGame
            WS_XML_STRING _doNegociationGameCompletedifficultyLocalName;  // difficulty
            WS_XML_STRING _doNegociationGameCompleteResponseTypeName;  // doNegociationGameCompleteResponse
            WS_XML_STRING _doNegociationGameCompleteResponsedoNegociationGameCompleteResultLocalName;  // doNegociationGameCompleteResult
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {  // _login
            {  // field description for username
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginusernameLocalName, // username
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_login, username),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username
            {  // field description for password
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginpasswordLocalName, // password
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_login, password),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for password
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_login, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _login
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs.username,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs.password,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs.securityPass,
            },
        },    // _login
        {  // _loginResponse
            {  // field description for loginResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginResponseloginResultLocalName, // loginResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loginResponse, loginResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for loginResult
            {  // fields description for _loginResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loginResponsedescs.loginResult,
            },
        },    // _loginResponse
        {  // _loadUserNetwork
            {  // field description for idUser
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkidUserLocalName, // idUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork, idUser),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idUser
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserNetwork
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs.idUser,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs.securityPass,
            },
        },    // _loadUserNetwork
        {  // _loadUserNetworkResponse
            {  // field description for loadUserNetworkResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseloadUserNetworkResultWrapperName, // loadUserNetworkResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
            WsOffsetOf(_loadUserNetworkResponse, loadUserNetworkResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_loadUserNetworkResponse, loadUserNetworkResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseloadUserNetworkResultLocalName, // UserType
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseloadUserNetworkResultNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            0,
            },    // end of field description for loadUserNetworkResult
            {  // fields description for _loadUserNetworkResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkResponsedescs.loadUserNetworkResult,
            },
        },    // _loadUserNetworkResponse
        {  // _loadUserNetwork_NR
            {  // field description for idUser
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkidUserLocalName, // idUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_NR, idUser),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idUser
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_NR, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserNetwork_NR
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs.idUser,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs.securityPass,
            },
        },    // _loadUserNetwork_NR
        {  // _loadUserNetwork_NRResponse
            {  // field description for loadUserNetwork_NRResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRResponseloadUserNetwork_NRResultLocalName, // loadUserNetwork_NRResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_NRResponse, loadUserNetwork_NRResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for loadUserNetwork_NRResult
            {  // fields description for _loadUserNetwork_NRResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRResponsedescs.loadUserNetwork_NRResult,
            },
        },    // _loadUserNetwork_NRResponse
        {  // _loadUserById
            {  // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserById, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserById, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserById
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs.id,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs.securityPass,
            },
        },    // _loadUserById
        {  // _loadUserByIdResponse
            {  // field description for loadUserByIdResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdResponseloadUserByIdResultLocalName, // loadUserByIdResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
            WsOffsetOf(_loadUserByIdResponse, loadUserByIdResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for loadUserByIdResult
            {  // fields description for _loadUserByIdResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIdResponsedescs.loadUserByIdResult,
            },
        },    // _loadUserByIdResponse
        {  // _changeUserPoints
            {  // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_changeUserPoints, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {  // field description for pointsToAdd
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeUserPointspointsToAddLocalName, // pointsToAdd
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_changeUserPoints, pointsToAdd),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for pointsToAdd
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_changeUserPoints, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _changeUserPoints
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsdescs.id,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsdescs.pointsToAdd,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsdescs.securityPass,
            },
        },    // _changeUserPoints
        {  // _changeUserPointsResponse
            {  // field description for changeUserPointsResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeUserPointsResponsechangeUserPointsResultLocalName, // changeUserPointsResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_changeUserPointsResponse, changeUserPointsResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for changeUserPointsResult
            {  // fields description for _changeUserPointsResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsResponsedescs.changeUserPointsResult,
            },
        },    // _changeUserPointsResponse
        {  // _changeMoodState
            {  // field description for idUser
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkidUserLocalName, // idUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_changeMoodState, idUser),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idUser
            {  // field description for mood
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeMoodStatemoodLocalName, // mood
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_changeMoodState, mood),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for mood
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_changeMoodState, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _changeMoodState
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStatedescs.idUser,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStatedescs.mood,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStatedescs.securityPass,
            },
        },    // _changeMoodState
        {  // _changeMoodStateResponse
            {  // field description for changeMoodStateResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeMoodStateResponsechangeMoodStateResultLocalName, // changeMoodStateResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_changeMoodStateResponse, changeMoodStateResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for changeMoodStateResult
            {  // fields description for _changeMoodStateResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStateResponsedescs.changeMoodStateResult,
            },
        },    // _changeMoodStateResponse
        {  // _doNegociationGameComplete
            {  // field description for userId_ONPLAY
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteuserId_ONPLAYLocalName, // userId_ONPLAY
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_doNegociationGameComplete, userId_ONPLAY),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for userId_ONPLAY
            {  // field description for UserIdB
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteUserIdBLocalName, // UserIdB
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_doNegociationGameComplete, UserIdB),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for UserIdB
            {  // field description for idGame
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteidGameLocalName, // idGame
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_doNegociationGameComplete, idGame),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idGame
            {  // field description for difficulty
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompletedifficultyLocalName, // difficulty
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_doNegociationGameComplete, difficulty),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for difficulty
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_doNegociationGameComplete, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _doNegociationGameComplete
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompletedescs.userId_ONPLAY,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompletedescs.UserIdB,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompletedescs.idGame,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompletedescs.difficulty,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompletedescs.securityPass,
            },
        },    // _doNegociationGameComplete
        {  // _doNegociationGameCompleteResponse
            {  // field description for doNegociationGameCompleteResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteResponsedoNegociationGameCompleteResultLocalName, // doNegociationGameCompleteResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
            WsOffsetOf(_doNegociationGameCompleteResponse, doNegociationGameCompleteResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for doNegociationGameCompleteResult
            {  // fields description for _doNegociationGameCompleteResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompleteResponsedescs.doNegociationGameCompleteResult,
            },
        },    // _doNegociationGameCompleteResponse
    }, // end of global elements
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("login",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("username",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("password",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("securityPass",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("loginResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("loginResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("idUser",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetworkResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("UserType",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/GameWS",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetworkResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_NR",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_NRResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_NRResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserById",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("id",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserByIdResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserByIdResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("changeUserPoints",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("pointsToAdd",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("changeUserPointsResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("changeUserPointsResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("changeMoodState",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("mood",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("changeMoodStateResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("changeMoodStateResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 27),
            WS_XML_STRING_DICTIONARY_VALUE("doNegociationGameComplete",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 28),
            WS_XML_STRING_DICTIONARY_VALUE("userId_ONPLAY",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 29),
            WS_XML_STRING_DICTIONARY_VALUE("UserIdB",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 30),
            WS_XML_STRING_DICTIONARY_VALUE("idGame",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 31),
            WS_XML_STRING_DICTIONARY_VALUE("difficulty",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 32),
            WS_XML_STRING_DICTIONARY_VALUE("doNegociationGameCompleteResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 33),
            WS_XML_STRING_DICTIONARY_VALUE("doNegociationGameCompleteResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 34),
        },  // end of xmlStrings
        
        {  // tempuri_org_xsddictionary
          // 94cab1e2-b266-4b7a-8d39-c689bf6d01ed 
        { 0x94cab1e2, 0xb266, 0x4b7a, { 0x8d, 0x39, 0xc6,0x89, 0xbf, 0x6d, 0x01, 0xed } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        35,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeName, // login
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.login,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginResponseTypeName, // loginResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loginResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkTypeName, // loadUserNetwork
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseTypeName, // loadUserNetworkResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetworkResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRTypeName, // loadUserNetwork_NR
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_NR,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRResponseTypeName, // loadUserNetwork_NRResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_NRResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdTypeName, // loadUserById
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserById,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdResponseTypeName, // loadUserByIdResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserByIdResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeUserPointsTypeName, // changeUserPoints
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.changeUserPoints,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeUserPointsResponseTypeName, // changeUserPointsResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.changeUserPointsResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeMoodStateTypeName, // changeMoodState
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.changeMoodState,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeMoodStateResponseTypeName, // changeMoodStateResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.changeMoodStateResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteTypeName, // doNegociationGameComplete
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.doNegociationGameComplete,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteResponseTypeName, // doNegociationGameCompleteResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.doNegociationGameCompleteResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_login),
        __alignof(_login),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs._loginFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._logindescs._loginFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeName, // login
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _login
        {
        sizeof(_loginResponse),
        __alignof(_loginResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loginResponsedescs._loginResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loginResponsedescs._loginResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginResponseTypeName, // loginResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loginResponse
        {
        sizeof(_loadUserNetwork),
        __alignof(_loadUserNetwork),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs._loadUserNetworkFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs._loadUserNetworkFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkTypeName, // loadUserNetwork
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork
        {
        sizeof(_loadUserNetworkResponse),
        __alignof(_loadUserNetworkResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkResponsedescs._loadUserNetworkResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkResponsedescs._loadUserNetworkResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseTypeName, // loadUserNetworkResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetworkResponse
        {
        sizeof(_loadUserNetwork_NR),
        __alignof(_loadUserNetwork_NR),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs._loadUserNetwork_NRFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs._loadUserNetwork_NRFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRTypeName, // loadUserNetwork_NR
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_NR
        {
        sizeof(_loadUserNetwork_NRResponse),
        __alignof(_loadUserNetwork_NRResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRResponsedescs._loadUserNetwork_NRResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRResponsedescs._loadUserNetwork_NRResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRResponseTypeName, // loadUserNetwork_NRResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_NRResponse
        {
        sizeof(_loadUserById),
        __alignof(_loadUserById),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs._loadUserByIdFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs._loadUserByIdFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdTypeName, // loadUserById
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserById
        {
        sizeof(_loadUserByIdResponse),
        __alignof(_loadUserByIdResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIdResponsedescs._loadUserByIdResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIdResponsedescs._loadUserByIdResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdResponseTypeName, // loadUserByIdResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserByIdResponse
        {
        sizeof(_changeUserPoints),
        __alignof(_changeUserPoints),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsdescs._changeUserPointsFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsdescs._changeUserPointsFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeUserPointsTypeName, // changeUserPoints
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _changeUserPoints
        {
        sizeof(_changeUserPointsResponse),
        __alignof(_changeUserPointsResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsResponsedescs._changeUserPointsResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._changeUserPointsResponsedescs._changeUserPointsResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeUserPointsResponseTypeName, // changeUserPointsResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _changeUserPointsResponse
        {
        sizeof(_changeMoodState),
        __alignof(_changeMoodState),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStatedescs._changeMoodStateFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStatedescs._changeMoodStateFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeMoodStateTypeName, // changeMoodState
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _changeMoodState
        {
        sizeof(_changeMoodStateResponse),
        __alignof(_changeMoodStateResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStateResponsedescs._changeMoodStateResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._changeMoodStateResponsedescs._changeMoodStateResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._changeMoodStateResponseTypeName, // changeMoodStateResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _changeMoodStateResponse
        {
        sizeof(_doNegociationGameComplete),
        __alignof(_doNegociationGameComplete),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompletedescs._doNegociationGameCompleteFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompletedescs._doNegociationGameCompleteFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteTypeName, // doNegociationGameComplete
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _doNegociationGameComplete
        {
        sizeof(_doNegociationGameCompleteResponse),
        __alignof(_doNegociationGameCompleteResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompleteResponsedescs._doNegociationGameCompleteResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._doNegociationGameCompleteResponsedescs._doNegociationGameCompleteResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._doNegociationGameCompleteResponseTypeName, // doNegociationGameCompleteResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _doNegociationGameCompleteResponse
    },  // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
