
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "System.xsd.h"
#include "GameWS.xsd.h"
#include "DataModel.Model.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _login
        {
            WS_FIELD_DESCRIPTION username;
            WS_FIELD_DESCRIPTION password;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loginFields [3]; 
        } _logindescs; // end of _login
        struct  // _loginResponse
        {
            WS_FIELD_DESCRIPTION loginResult;
            WS_FIELD_DESCRIPTION* _loginResponseFields [1]; 
        } _loginResponsedescs; // end of _loginResponse
        struct  // _loadUserNetwork
        {
            WS_FIELD_DESCRIPTION idUser;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserNetworkFields [2]; 
        } _loadUserNetworkdescs; // end of _loadUserNetwork
        struct  // _loadUserNetworkResponse
        {
            WS_FIELD_DESCRIPTION loadUserNetworkResult;
            WS_FIELD_DESCRIPTION* _loadUserNetworkResponseFields [1]; 
        } _loadUserNetworkResponsedescs; // end of _loadUserNetworkResponse
        struct  // _loadUserNetwork_2
        {
            WS_FIELD_DESCRIPTION idUser;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_2Fields [2]; 
        } _loadUserNetwork_2descs; // end of _loadUserNetwork_2
        struct  // _loadUserNetwork_2Response
        {
            WS_FIELD_DESCRIPTION loadUserNetwork_2Result;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_2ResponseFields [1]; 
        } _loadUserNetwork_2Responsedescs; // end of _loadUserNetwork_2Response
        struct  // _loadUserNetwork_3
        {
            WS_FIELD_DESCRIPTION idUser;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_3Fields [2]; 
        } _loadUserNetwork_3descs; // end of _loadUserNetwork_3
        struct  // _loadUserNetwork_3Response
        {
            WS_FIELD_DESCRIPTION loadUserNetwork_3Result;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_3ResponseFields [1]; 
        } _loadUserNetwork_3Responsedescs; // end of _loadUserNetwork_3Response
        struct  // _loadUserNetwork_NR
        {
            WS_FIELD_DESCRIPTION idUser;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_NRFields [2]; 
        } _loadUserNetwork_NRdescs; // end of _loadUserNetwork_NR
        struct  // _loadUserNetwork_NRResponse
        {
            WS_FIELD_DESCRIPTION loadUserNetwork_NRResult;
            WS_FIELD_DESCRIPTION* _loadUserNetwork_NRResponseFields [1]; 
        } _loadUserNetwork_NRResponsedescs; // end of _loadUserNetwork_NRResponse
        struct  // _loadUserById
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION securityPass;
            WS_FIELD_DESCRIPTION* _loadUserByIdFields [2]; 
        } _loadUserByIddescs; // end of _loadUserById
        struct  // _loadUserByIdResponse
        {
            WS_FIELD_DESCRIPTION loadUserByIdResult;
            WS_FIELD_DESCRIPTION* _loadUserByIdResponseFields [1]; 
        } _loadUserByIdResponsedescs; // end of _loadUserByIdResponse
    } globalElements;  // end of global elements
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _loginTypeName;  // login
            WS_XML_STRING _loginTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _loginusernameLocalName;  // username
            WS_XML_STRING _loginpasswordLocalName;  // password
            WS_XML_STRING _loginsecurityPassLocalName;  // securityPass
            WS_XML_STRING _loginResponseTypeName;  // loginResponse
            WS_XML_STRING _loginResponseloginResultLocalName;  // loginResult
            WS_XML_STRING _loadUserNetworkTypeName;  // loadUserNetwork
            WS_XML_STRING _loadUserNetworkidUserLocalName;  // idUser
            WS_XML_STRING _loadUserNetworkResponseTypeName;  // loadUserNetworkResponse
            WS_XML_STRING _loadUserNetworkResponseloadUserNetworkResultLocalName;  // UserType
            WS_XML_STRING _loadUserNetworkResponseloadUserNetworkResultNamespace;  // http://schemas.datacontract.org/2004/07/GameWS
            WS_XML_STRING _loadUserNetworkResponseloadUserNetworkResultWrapperName;  // loadUserNetworkResult
            WS_XML_STRING _loadUserNetwork_2TypeName;  // loadUserNetwork_2
            WS_XML_STRING _loadUserNetwork_2ResponseTypeName;  // loadUserNetwork_2Response
            WS_XML_STRING _loadUserNetwork_2ResponseloadUserNetwork_2ResultLocalName;  // User
            WS_XML_STRING _loadUserNetwork_2ResponseloadUserNetwork_2ResultNamespace;  // http://schemas.datacontract.org/2004/07/DataModel.Model
            WS_XML_STRING _loadUserNetwork_2ResponseloadUserNetwork_2ResultWrapperName;  // loadUserNetwork_2Result
            WS_XML_STRING _loadUserNetwork_3TypeName;  // loadUserNetwork_3
            WS_XML_STRING _loadUserNetwork_3ResponseTypeName;  // loadUserNetwork_3Response
            WS_XML_STRING _loadUserNetwork_3ResponseloadUserNetwork_3ResultLocalName;  // loadUserNetwork_3Result
            WS_XML_STRING _loadUserNetwork_NRTypeName;  // loadUserNetwork_NR
            WS_XML_STRING _loadUserNetwork_NRResponseTypeName;  // loadUserNetwork_NRResponse
            WS_XML_STRING _loadUserNetwork_NRResponseloadUserNetwork_NRResultLocalName;  // loadUserNetwork_NRResult
            WS_XML_STRING _loadUserByIdTypeName;  // loadUserById
            WS_XML_STRING _loadUserByIdidLocalName;  // id
            WS_XML_STRING _loadUserByIdResponseTypeName;  // loadUserByIdResponse
            WS_XML_STRING _loadUserByIdResponseloadUserByIdResultLocalName;  // loadUserByIdResult
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {  // _login
            {  // field description for username
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginusernameLocalName, // username
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_login, username),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for username
            {  // field description for password
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginpasswordLocalName, // password
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_login, password),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for password
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_login, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _login
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs.username,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs.password,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs.securityPass,
            },
        },    // _login
        {  // _loginResponse
            {  // field description for loginResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginResponseloginResultLocalName, // loginResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loginResponse, loginResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for loginResult
            {  // fields description for _loginResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loginResponsedescs.loginResult,
            },
        },    // _loginResponse
        {  // _loadUserNetwork
            {  // field description for idUser
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkidUserLocalName, // idUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork, idUser),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idUser
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserNetwork
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs.idUser,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs.securityPass,
            },
        },    // _loadUserNetwork
        {  // _loadUserNetworkResponse
            {  // field description for loadUserNetworkResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseloadUserNetworkResultWrapperName, // loadUserNetworkResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
            WsOffsetOf(_loadUserNetworkResponse, loadUserNetworkResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_loadUserNetworkResponse, loadUserNetworkResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseloadUserNetworkResultLocalName, // UserType
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseloadUserNetworkResultNamespace, // http://schemas.datacontract.org/2004/07/GameWS
            0,
            },    // end of field description for loadUserNetworkResult
            {  // fields description for _loadUserNetworkResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkResponsedescs.loadUserNetworkResult,
            },
        },    // _loadUserNetworkResponse
        {  // _loadUserNetwork_2
            {  // field description for idUser
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkidUserLocalName, // idUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_2, idUser),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idUser
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_2, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserNetwork_2
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_2descs.idUser,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_2descs.securityPass,
            },
        },    // _loadUserNetwork_2
        {  // _loadUserNetwork_2Response
            {  // field description for loadUserNetwork_2Result
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_2ResponseloadUserNetwork_2ResultWrapperName, // loadUserNetwork_2Result
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&DataModel_Model_xsd.globalTypes.User,
            WsOffsetOf(_loadUserNetwork_2Response, loadUserNetwork_2Result),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_loadUserNetwork_2Response, loadUserNetwork_2ResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_2ResponseloadUserNetwork_2ResultLocalName, // User
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_2ResponseloadUserNetwork_2ResultNamespace, // http://schemas.datacontract.org/2004/07/DataModel.Model
            0,
            },    // end of field description for loadUserNetwork_2Result
            {  // fields description for _loadUserNetwork_2Response
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_2Responsedescs.loadUserNetwork_2Result,
            },
        },    // _loadUserNetwork_2Response
        {  // _loadUserNetwork_3
            {  // field description for idUser
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkidUserLocalName, // idUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_3, idUser),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idUser
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_3, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserNetwork_3
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_3descs.idUser,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_3descs.securityPass,
            },
        },    // _loadUserNetwork_3
        {  // _loadUserNetwork_3Response
            {  // field description for loadUserNetwork_3Result
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_3ResponseloadUserNetwork_3ResultLocalName, // loadUserNetwork_3Result
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_3Response, loadUserNetwork_3Result),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for loadUserNetwork_3Result
            {  // fields description for _loadUserNetwork_3Response
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_3Responsedescs.loadUserNetwork_3Result,
            },
        },    // _loadUserNetwork_3Response
        {  // _loadUserNetwork_NR
            {  // field description for idUser
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkidUserLocalName, // idUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_NR, idUser),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for idUser
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_NR, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserNetwork_NR
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs.idUser,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs.securityPass,
            },
        },    // _loadUserNetwork_NR
        {  // _loadUserNetwork_NRResponse
            {  // field description for loadUserNetwork_NRResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRResponseloadUserNetwork_NRResultLocalName, // loadUserNetwork_NRResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserNetwork_NRResponse, loadUserNetwork_NRResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for loadUserNetwork_NRResult
            {  // fields description for _loadUserNetwork_NRResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRResponsedescs.loadUserNetwork_NRResult,
            },
        },    // _loadUserNetwork_NRResponse
        {  // _loadUserById
            {  // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_loadUserById, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {  // field description for securityPass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginsecurityPassLocalName, // securityPass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_loadUserById, securityPass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for securityPass
            {  // fields description for _loadUserById
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs.id,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs.securityPass,
            },
        },    // _loadUserById
        {  // _loadUserByIdResponse
            {  // field description for loadUserByIdResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdResponseloadUserByIdResultLocalName, // loadUserByIdResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&GameWS_xsd.globalTypes.UserType,
            WsOffsetOf(_loadUserByIdResponse, loadUserByIdResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for loadUserByIdResult
            {  // fields description for _loadUserByIdResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIdResponsedescs.loadUserByIdResult,
            },
        },    // _loadUserByIdResponse
    }, // end of global elements
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("login",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("username",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("password",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("securityPass",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("loginResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("loginResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("idUser",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetworkResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("UserType",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/GameWS",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetworkResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_2",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_2Response",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("User",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/DataModel.Model",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_2Result",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_3",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_3Response",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_3Result",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_NR",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_NRResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserNetwork_NRResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserById",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("id",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserByIdResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("loadUserByIdResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 27),
        },  // end of xmlStrings
        
        {  // tempuri_org_xsddictionary
          // 491bc52c-fac5-44f5-9040-1b2fd0231c2b 
        { 0x491bc52c, 0xfac5, 0x44f5, { 0x90, 0x40, 0x1b,0x2f, 0xd0, 0x23, 0x1c, 0x2b } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        28,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeName, // login
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.login,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginResponseTypeName, // loginResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loginResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkTypeName, // loadUserNetwork
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseTypeName, // loadUserNetworkResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetworkResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_2TypeName, // loadUserNetwork_2
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_2,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_2ResponseTypeName, // loadUserNetwork_2Response
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_2Response,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_3TypeName, // loadUserNetwork_3
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_3,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_3ResponseTypeName, // loadUserNetwork_3Response
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_3Response,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRTypeName, // loadUserNetwork_NR
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_NR,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRResponseTypeName, // loadUserNetwork_NRResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserNetwork_NRResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdTypeName, // loadUserById
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserById,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdResponseTypeName, // loadUserByIdResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.loadUserByIdResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_login),
        __alignof(_login),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._logindescs._loginFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._logindescs._loginFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeName, // login
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _login
        {
        sizeof(_loginResponse),
        __alignof(_loginResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loginResponsedescs._loginResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loginResponsedescs._loginResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginResponseTypeName, // loginResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loginResponse
        {
        sizeof(_loadUserNetwork),
        __alignof(_loadUserNetwork),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs._loadUserNetworkFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkdescs._loadUserNetworkFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkTypeName, // loadUserNetwork
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork
        {
        sizeof(_loadUserNetworkResponse),
        __alignof(_loadUserNetworkResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkResponsedescs._loadUserNetworkResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetworkResponsedescs._loadUserNetworkResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetworkResponseTypeName, // loadUserNetworkResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetworkResponse
        {
        sizeof(_loadUserNetwork_2),
        __alignof(_loadUserNetwork_2),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_2descs._loadUserNetwork_2Fields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_2descs._loadUserNetwork_2Fields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_2TypeName, // loadUserNetwork_2
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_2
        {
        sizeof(_loadUserNetwork_2Response),
        __alignof(_loadUserNetwork_2Response),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_2Responsedescs._loadUserNetwork_2ResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_2Responsedescs._loadUserNetwork_2ResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_2ResponseTypeName, // loadUserNetwork_2Response
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_2Response
        {
        sizeof(_loadUserNetwork_3),
        __alignof(_loadUserNetwork_3),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_3descs._loadUserNetwork_3Fields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_3descs._loadUserNetwork_3Fields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_3TypeName, // loadUserNetwork_3
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_3
        {
        sizeof(_loadUserNetwork_3Response),
        __alignof(_loadUserNetwork_3Response),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_3Responsedescs._loadUserNetwork_3ResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_3Responsedescs._loadUserNetwork_3ResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_3ResponseTypeName, // loadUserNetwork_3Response
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_3Response
        {
        sizeof(_loadUserNetwork_NR),
        __alignof(_loadUserNetwork_NR),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs._loadUserNetwork_NRFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRdescs._loadUserNetwork_NRFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRTypeName, // loadUserNetwork_NR
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_NR
        {
        sizeof(_loadUserNetwork_NRResponse),
        __alignof(_loadUserNetwork_NRResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRResponsedescs._loadUserNetwork_NRResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserNetwork_NRResponsedescs._loadUserNetwork_NRResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserNetwork_NRResponseTypeName, // loadUserNetwork_NRResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserNetwork_NRResponse
        {
        sizeof(_loadUserById),
        __alignof(_loadUserById),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs._loadUserByIdFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIddescs._loadUserByIdFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdTypeName, // loadUserById
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserById
        {
        sizeof(_loadUserByIdResponse),
        __alignof(_loadUserByIdResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIdResponsedescs._loadUserByIdResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._loadUserByIdResponsedescs._loadUserByIdResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loadUserByIdResponseTypeName, // loadUserByIdResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._loginTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _loadUserByIdResponse
    },  // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
