user('Matt').
user_tags('Matt','C#').
user_tags('Matt','Tecnology').
friend('Matt','Albert').
user_tags('Albert','FCP').
user_tags('Albert','ISEP').
friend('Matt','Joe').
user_tags('Joe','SLB').
user_tags('Joe','FEUP').
friend('Matt','Alex').
user_tags('Alex','Youtube').
