user('Matt').
friends('Matt','Albert').
friends('Matt','Joe').
friends('Matt','Alex').
user_tags('Matt','C#').
user_tags('Matt','Tecnology').
user_tags('Albert','FCP').
user_tags('Albert','ISEP').
user_tags('Joe','SLB').
user_tags('Joe','FEUP').
user_tags('Alex','Youtube').
