//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebServiceDemo.WebServiceDemoNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceDemoNS.IServiceDemo")]
    public interface IServiceDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/DoWork", ReplyAction="http://tempuri.org/IServiceDemo/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/DoWork", ReplyAction="http://tempuri.org/IServiceDemo/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/Add", ReplyAction="http://tempuri.org/IServiceDemo/AddResponse")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/Add", ReplyAction="http://tempuri.org/IServiceDemo/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDemoChannel : ClienteWebServiceDemo.WebServiceDemoNS.IServiceDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDemoClient : System.ServiceModel.ClientBase<ClienteWebServiceDemo.WebServiceDemoNS.IServiceDemo>, ClienteWebServiceDemo.WebServiceDemoNS.IServiceDemo {
        
        public ServiceDemoClient() {
        }
        
        public ServiceDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
    }
}
